#include "c_emitter.h"
#include <cstdarg>
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <cstring>
#include <cctype>
#include <cstdint>
#include <algorithm>
#include <unordered_set>

// Call model: recomp→recomp calls and returns stay on the native C stack. `bl`/
// `bctrl` emit an inline C call that *continues* after the callee returns; `blr`
// emits a C `return`; `b`/`bctr` that leave the function emit `tail_ppc`. The
// runtime (call_ppc/tail_ppc/SunbrightBridge::Run, runtime/dolphin_hook.cpp) bridges
// to Dolphin for non-recompiled targets.

// PPC rotate-word mask MASK(mb, me): set bits mb..me inclusive in big-endian bit
// numbering (MSB = bit 0 = C bit 31), WRAPPING when mb > me (bits mb..31 and
// 0..me). Iterating with wraparound is correct for both cases — the old
// "build [31-me,31-mb] then complement when mb>me" trick only worked when the
// gap was empty (mb==me+1) and silently produced 0xFFFFFFFF for real wrap masks
// like `rlwinm rX,rX,0,31,29` (clear one bit), which then cleared nothing.
static u32 ppc_rotate_mask(u32 mb, u32 me) {
    u32 m = 0;
    for (u32 b = mb;; b = (b + 1) & 31) {
        m |= (0x80000000u >> b);
        if (b == me) break;
    }
    return m;
}

void CEmitter::line(const char* fmt, ...) {
    char buf[512];
    va_list ap;
    va_start(ap, fmt);
    vsnprintf(buf, sizeof(buf), fmt, ap);
    va_end(ap);
    out_ << "    " << buf << "\n";
}

void CEmitter::emit_header() {
    out_ << R"(// AUTO-GENERATED by sunbright-recomp — DO NOT EDIT
// Regenerate with: /recompile
#include "../runtime/cpu_state.h"
#include "../runtime/intrinsics.h"
#include <cstdint>
#include <cmath>

// Forward declarations for all functions in this translation unit
)";
}

void CEmitter::emit_jump_table(const std::vector<u32>& func_addrs) {
    out_ << "// AUTO-GENERATED jump table — DO NOT EDIT\n";
    out_ << "#include \"../runtime/cpu_state.h\"\n";
    out_ << "#include <cstddef>\n\n";
    out_ << "using RecompFunc = void (*)(CPUState&);\n\n";

    for (u32 addr : func_addrs)
        out_ << "extern \"C\" void func_" << std::hex << addr << "(CPUState&);\n";

    out_ << "\nstruct JumpEntry { uint32_t addr; RecompFunc fn; };\n";
    out_ << "extern \"C\" const JumpEntry g_recomp_table[] = {\n";
    for (u32 addr : func_addrs)
        out_ << "    { 0x" << std::hex << addr << "u, func_" << addr << " },\n";
    out_ << "    { 0, nullptr }\n};\n";
    out_ << "extern \"C\" const size_t g_recomp_table_size = " << std::dec << func_addrs.size() << "u;\n";
}

std::string CEmitter::ea(const PPCInstr& i) {
    if (i.rA == 0) {
        char buf[32];
        snprintf(buf, sizeof(buf), "0x%xu", (u32)(s32)i.d);
        return buf;
    }
    char buf[64];
    if (i.d == 0)
        snprintf(buf, sizeof(buf), "cpu.gpr[%d]", i.rA);
    else
        snprintf(buf, sizeof(buf), "cpu.gpr[%d] + %d", i.rA, (int)i.d);
    return buf;
}

std::string CEmitter::ea_x(const PPCInstr& i) {
    if (i.rA == 0) {
        char buf[32];
        snprintf(buf, sizeof(buf), "cpu.gpr[%d]", i.rB);
        return buf;
    }
    char buf[64];
    snprintf(buf, sizeof(buf), "cpu.gpr[%d] + cpu.gpr[%d]", i.rA, i.rB);
    return buf;
}

std::string CEmitter::cr_bit(u8 bi) {
    const char* fields[] = {"lt","gt","eq","so"};
    char buf[32];
    snprintf(buf, sizeof(buf), "cpu.cr[%d].%s", bi / 4, fields[bi % 4]);
    return buf;
}

void CEmitter::set_cr0(const PPCInstr& i, const std::string& result) {
    if (i.rc)
        line("update_cr0(cpu, (s32)(%s));", result.c_str());
}

void CEmitter::emit_function(const EmitContext& ctx) {
    out_ << "\nextern \"C\" void func_" << std::hex << ctx.func_addr
         << "(CPUState& cpu) {\n";

    for (const auto& i : ctx.instrs) {
        // Emit label if this is a branch target within the function
        if (ctx.branch_targets.count(i.pc))
            out_ << "lbl_" << std::hex << i.pc << ":\n";

        // Emit a comment with the PC for debugging
        out_ << "    // " << std::hex << i.pc << "\n";

        emit_instr(i, ctx);
    }

    out_ << "}\n";
}

void CEmitter::emit_instr(const PPCInstr& i, const EmitContext& ctx) {
    const std::string d = "cpu.gpr[" + std::to_string(i.rD) + "]";
    const std::string a = "cpu.gpr[" + std::to_string(i.rA) + "]";
    const std::string b = "cpu.gpr[" + std::to_string(i.rB) + "]";
    const std::string s = "cpu.gpr[" + std::to_string(i.rS) + "]";

    const std::string fd  = "cpu.fpr[" + std::to_string(i.rD) + "].ps0";
    const std::string fa  = "cpu.fpr[" + std::to_string(i.rA) + "].ps0";
    const std::string fb  = "cpu.fpr[" + std::to_string(i.rB) + "].ps0";
    const std::string fc  = "cpu.fpr[" + std::to_string(i.rC) + "].ps0";

    const std::string psd0 = "cpu.fpr[" + std::to_string(i.rD) + "].ps0";
    const std::string psd1 = "cpu.fpr[" + std::to_string(i.rD) + "].ps1";
    const std::string psa0 = "cpu.fpr[" + std::to_string(i.rA) + "].ps0";
    const std::string psa1 = "cpu.fpr[" + std::to_string(i.rA) + "].ps1";
    const std::string psb0 = "cpu.fpr[" + std::to_string(i.rB) + "].ps0";
    const std::string psb1 = "cpu.fpr[" + std::to_string(i.rB) + "].ps1";
    const std::string psc0 = "cpu.fpr[" + std::to_string(i.rC) + "].ps0";
    const std::string psc1 = "cpu.fpr[" + std::to_string(i.rC) + "].ps1";

    switch (i.op) {
    // ── Integer arithmetic ──────────────────────────────────────────────────
    case PPCOp::ADDI:
        if (i.rA == 0)
            line("%s = %d;", d.c_str(), (int)i.simm);
        else
            line("%s = %s + %d;", d.c_str(), a.c_str(), (int)i.simm);
        break;

    case PPCOp::ADDIS:
        if (i.rA == 0)
            line("%s = 0x%xu;", d.c_str(), (u32)i.uimm << 16);
        else
            line("%s = %s + 0x%xu;", d.c_str(), a.c_str(), (u32)i.uimm << 16);
        break;

    case PPCOp::ADD:
        line("%s = %s + %s;", d.c_str(), a.c_str(), b.c_str());
        set_cr0(i, d);
        break;

    case PPCOp::ADDO:
        line("{ u32 _r = %s + %s; cpu.xer.ov = add_overflow(%s,%s,_r); cpu.xer.so|=cpu.xer.ov; %s=_r; }",
             a.c_str(), b.c_str(), a.c_str(), b.c_str(), d.c_str());
        set_cr0(i, d);
        break;

    case PPCOp::ADDIC:  // addic: rA + SIMM, set CA (immediate form)
        line("{ u32 _r = %s + %d; cpu.xer.ca = add_carry(%s,(u32)%d); %s=_r; }",
             a.c_str(), (int)i.simm, a.c_str(), (int)i.simm, d.c_str());
        set_cr0(i, d);
        break;
    case PPCOp::ADDC:   // addc: rA + rB, set CA (register form)
        line("{ u32 _r = %s + %s; cpu.xer.ca = add_carry(%s,%s); %s=_r; }",
             a.c_str(), b.c_str(), a.c_str(), b.c_str(), d.c_str());
        set_cr0(i, d);
        break;

    case PPCOp::ADDE:
        line("{ u32 _r = %s + %s + cpu.xer.ca; cpu.xer.ca = add_carry3(%s,%s,cpu.xer.ca); %s=_r; }",
             a.c_str(), b.c_str(), a.c_str(), b.c_str(), d.c_str());
        set_cr0(i, d);
        break;

    case PPCOp::ADDME:
        line("{ u32 _r = %s + 0xFFFFFFFFu + cpu.xer.ca; cpu.xer.ca = add_carry3(%s,0xFFFFFFFFu,cpu.xer.ca); %s=_r; }",
             a.c_str(), a.c_str(), d.c_str());
        set_cr0(i, d);
        break;

    case PPCOp::ADDZE:
        line("{ u32 _r = %s + cpu.xer.ca; cpu.xer.ca = add_carry(%s,cpu.xer.ca); %s=_r; }",
             a.c_str(), a.c_str(), d.c_str());
        set_cr0(i, d);
        break;

    case PPCOp::SUBF:
        line("%s = %s - %s;", d.c_str(), b.c_str(), a.c_str());
        set_cr0(i, d);
        break;

    case PPCOp::SUBFIC:
        line("{ u32 _r = %d - (s32)%s; cpu.xer.ca = sub_carry((u32)%d, %s); %s=_r; }",
             (int)i.simm, a.c_str(), (int)i.simm, a.c_str(), d.c_str());
        break;

    case PPCOp::SUBFC:
        line("{ u32 _r = %s - %s; cpu.xer.ca = sub_carry(%s,%s); %s=_r; }",
             b.c_str(), a.c_str(), b.c_str(), a.c_str(), d.c_str());
        set_cr0(i, d);
        break;

    case PPCOp::SUBFE:
        line("{ u32 _r = ~%s + %s + cpu.xer.ca; cpu.xer.ca = add_carry3(~%s,%s,cpu.xer.ca); %s=_r; }",
             a.c_str(), b.c_str(), a.c_str(), b.c_str(), d.c_str());
        set_cr0(i, d);
        break;

    case PPCOp::SUBFZE:
        line("{ u32 _r = ~%s + cpu.xer.ca; cpu.xer.ca = add_carry(~%s,cpu.xer.ca); %s=_r; }",
             a.c_str(), a.c_str(), d.c_str());
        set_cr0(i, d);
        break;

    case PPCOp::SUBFME:
        line("{ u32 _r = ~%s + 0xFFFFFFFFu + cpu.xer.ca; cpu.xer.ca = add_carry3(~%s,0xFFFFFFFFu,cpu.xer.ca); %s=_r; }",
             a.c_str(), a.c_str(), d.c_str());
        set_cr0(i, d);
        break;

    case PPCOp::NEG:
        line("%s = -(s32)%s;", d.c_str(), a.c_str());
        set_cr0(i, d);
        break;

    case PPCOp::MULLI:
        line("%s = (s32)%s * %d;", d.c_str(), a.c_str(), (int)i.simm);
        break;

    case PPCOp::MULLW:
        line("%s = (u32)((s32)%s * (s32)%s);", d.c_str(), a.c_str(), b.c_str());
        set_cr0(i, d);
        break;

    case PPCOp::MULHW:
        line("%s = (u32)((int64_t)(s32)%s * (s32)%s >> 32);", d.c_str(), a.c_str(), b.c_str());
        set_cr0(i, d);
        break;

    case PPCOp::MULHWU:
        line("%s = (u32)((uint64_t)%s * %s >> 32);", d.c_str(), a.c_str(), b.c_str());
        set_cr0(i, d);
        break;

    case PPCOp::DIVW:
        line("if (%s != 0) %s = (u32)((s32)%s / (s32)%s);", b.c_str(), d.c_str(), a.c_str(), b.c_str());
        set_cr0(i, d);
        break;

    case PPCOp::DIVWU:
        line("if (%s != 0) %s = %s / %s;", b.c_str(), d.c_str(), a.c_str(), b.c_str());
        set_cr0(i, d);
        break;

    // ── Compare ─────────────────────────────────────────────────────────────
    case PPCOp::CMP:
        line("{ s32 _a=(s32)%s,_b=(s32)%s; cpu.cr[%d].lt=_a<_b; cpu.cr[%d].gt=_a>_b; cpu.cr[%d].eq=_a==_b; cpu.cr[%d].so=cpu.xer.so; }",
             a.c_str(), b.c_str(), i.crfD, i.crfD, i.crfD, i.crfD);
        break;

    case PPCOp::CMPI:
        line("{ s32 _a=(s32)%s,_b=%d; cpu.cr[%d].lt=_a<_b; cpu.cr[%d].gt=_a>_b; cpu.cr[%d].eq=_a==_b; cpu.cr[%d].so=cpu.xer.so; }",
             a.c_str(), (int)i.simm, i.crfD, i.crfD, i.crfD, i.crfD);
        break;

    case PPCOp::CMPL:
        line("{ u32 _a=%s,_b=%s; cpu.cr[%d].lt=_a<_b; cpu.cr[%d].gt=_a>_b; cpu.cr[%d].eq=_a==_b; cpu.cr[%d].so=cpu.xer.so; }",
             a.c_str(), b.c_str(), i.crfD, i.crfD, i.crfD, i.crfD);
        break;

    case PPCOp::CMPLI:
        line("{ u32 _a=%s,_b=0x%xu; cpu.cr[%d].lt=_a<_b; cpu.cr[%d].gt=_a>_b; cpu.cr[%d].eq=_a==_b; cpu.cr[%d].so=cpu.xer.so; }",
             a.c_str(), (u32)i.uimm, i.crfD, i.crfD, i.crfD, i.crfD);
        break;

    // ── Logical ─────────────────────────────────────────────────────────────
    case PPCOp::AND:
        line("%s = %s & %s;", a.c_str(), s.c_str(), b.c_str());
        set_cr0(i, a);
        break;
    case PPCOp::ANDI_DOT:
        line("%s = %s & 0x%xu;", a.c_str(), s.c_str(), (u32)i.uimm);
        line("update_cr0(cpu, (s32)%s);", a.c_str());
        break;
    case PPCOp::ANDIS_DOT:
        line("%s = %s & 0x%xu;", a.c_str(), s.c_str(), (u32)i.uimm << 16);
        line("update_cr0(cpu, (s32)%s);", a.c_str());
        break;
    case PPCOp::ANDC:
        line("%s = %s & ~%s;", a.c_str(), s.c_str(), b.c_str());
        set_cr0(i, a);
        break;
    case PPCOp::OR:
        line("%s = %s | %s;", a.c_str(), s.c_str(), b.c_str());
        set_cr0(i, a);
        break;
    case PPCOp::ORI:
        line("%s = %s | 0x%xu;", a.c_str(), s.c_str(), (u32)i.uimm);
        break;
    case PPCOp::ORIS:
        line("%s = %s | 0x%xu;", a.c_str(), s.c_str(), (u32)i.uimm << 16);
        break;
    case PPCOp::ORC:
        line("%s = %s | ~%s;", a.c_str(), s.c_str(), b.c_str());
        set_cr0(i, a);
        break;
    case PPCOp::XOR:
        line("%s = %s ^ %s;", a.c_str(), s.c_str(), b.c_str());
        set_cr0(i, a);
        break;
    case PPCOp::XORI:
        line("%s = %s ^ 0x%xu;", a.c_str(), s.c_str(), (u32)i.uimm);
        break;
    case PPCOp::XORIS:
        line("%s = %s ^ 0x%xu;", a.c_str(), s.c_str(), (u32)i.uimm << 16);
        break;
    case PPCOp::NOR:
        line("%s = ~(%s | %s);", a.c_str(), s.c_str(), b.c_str());
        set_cr0(i, a);
        break;
    case PPCOp::NAND:
        line("%s = ~(%s & %s);", a.c_str(), s.c_str(), b.c_str());
        set_cr0(i, a);
        break;
    case PPCOp::EQV:
        line("%s = ~(%s ^ %s);", a.c_str(), s.c_str(), b.c_str());
        set_cr0(i, a);
        break;
    case PPCOp::EXTSB:
        line("%s = (u32)(s32)(s8)%s;", a.c_str(), s.c_str());
        set_cr0(i, a);
        break;
    case PPCOp::EXTSH:
        line("%s = (u32)(s32)(s16)%s;", a.c_str(), s.c_str());
        set_cr0(i, a);
        break;
    case PPCOp::CNTLZW:
        line("%s = %s ? __builtin_clz(%s) : 32;", a.c_str(), s.c_str(), s.c_str());
        set_cr0(i, a);
        break;

    // ── Rotate/shift ────────────────────────────────────────────────────────
    case PPCOp::RLWINM: {
        u32 mask = ppc_rotate_mask(i.mb, i.me);
        line("%s = rotl32(%s, %d) & 0x%xu;", a.c_str(), s.c_str(), i.sh, mask);
        set_cr0(i, a);
        break;
    }
    case PPCOp::RLWIMI: {
        u32 mask = ppc_rotate_mask(i.mb, i.me);
        line("%s = (rotl32(%s, %d) & 0x%xu) | (%s & ~0x%xu);",
             a.c_str(), s.c_str(), i.sh, mask, a.c_str(), mask);
        set_cr0(i, a);
        break;
    }
    case PPCOp::RLWNM: {
        u32 mask = ppc_rotate_mask(i.mb, i.me);
        line("%s = rotl32(%s, %s & 0x1F) & 0x%xu;", a.c_str(), s.c_str(), b.c_str(), mask);
        set_cr0(i, a);
        break;
    }
    case PPCOp::SLW:
        line("%s = (%s & 0x20) ? 0 : (%s << (%s & 0x1F));", a.c_str(), b.c_str(), s.c_str(), b.c_str());
        set_cr0(i, a);
        break;
    case PPCOp::SRW:
        line("%s = (%s & 0x20) ? 0 : (%s >> (%s & 0x1F));", a.c_str(), b.c_str(), s.c_str(), b.c_str());
        set_cr0(i, a);
        break;
    case PPCOp::SRAW:
        line("{ u32 _n=%s&0x3F; %s=(%s&0x20)?(s32)%s>>31:((s32)%s>>_n); cpu.xer.ca=(s32)%s<0&&(%s&((1u<<_n)-1))!=0; }",
             b.c_str(), a.c_str(), b.c_str(), s.c_str(), s.c_str(), s.c_str(), s.c_str());
        set_cr0(i, a);
        break;
    case PPCOp::SRAWI:
        line("{ %s=(s32)%s>>%d; cpu.xer.ca=(s32)%s<0&&(%s&0x%xu)!=0; }",
             a.c_str(), s.c_str(), i.sh, s.c_str(), s.c_str(), (1u << i.sh) - 1);
        set_cr0(i, a);
        break;

    // ── Branches ────────────────────────────────────────────────────────────
    case PPCOp::B: {
        bool intra = ctx.branch_targets.count(i.target) > 0;
        if (i.lk) {
            line("cpu.lr = 0x%xu;", i.pc + 4);
            line("call_ppc(cpu, 0x%xu);", i.target);          // call, continue inline
        } else if (intra) {
            line("goto lbl_%x;", i.target);
        } else if (i.target != 0) {
            line("tail_ppc(cpu, 0x%xu); return;", i.target);  // tail branch out of the function (`b target`)
        } else {
            line("return; // indirect unconditional branch");
        }
        break;
    }

    case PPCOp::BC: {
        bool ctr_decr   = !(i.bo & 0x04);
        bool ctr_zero   = (i.bo & 0x02);
        bool cond_true  = (i.bo & 0x08);
        bool cond_ignore = (i.bo & 0x10);

        std::string parts;
        if (ctr_decr) {
            line("cpu.ctr--;");
            parts = ctr_zero ? "(cpu.ctr == 0)" : "(cpu.ctr != 0)";
        }
        if (!cond_ignore) {
            std::string cc = cr_bit(i.bi);
            std::string cc_cond = cond_true ? cc : ("!" + cc);
            parts = parts.empty() ? cc_cond : (parts + " && " + cc_cond);
        }
        if (parts.empty()) parts = "true";

        bool intra = ctx.branch_targets.count(i.target) > 0;
        if (i.lk) {
            line("if (%s) { cpu.lr = 0x%xu; call_ppc(cpu, 0x%xu); }", parts.c_str(), i.pc + 4, i.target);
        } else if (intra) {
            line("if (%s) goto lbl_%x;", parts.c_str(), i.target);
        } else {
            // conditional tail branch out of the function
            line("if (%s) { tail_ppc(cpu, 0x%xu); return; }", parts.c_str(), i.target);
        }
        break;
    }

    case PPCOp::BCLR:
        if (i.bo == 0x14) {  // always blr
            if (i.lk) {
                // blrl: save return addr in LR, then call old LR (continues inline).
                line("{ u32 _tgt = cpu.lr; cpu.lr = 0x%xu; call_ppc(cpu, _tgt); }", i.pc + 4);
            } else {
                line("return;");  // blr → C return
            }
        } else {
            // Conditional blr — complex BO decode
            if (!(i.bo & 4)) line("cpu.ctr--;");
            std::string cond = "true";
            if (!(i.bo & 0x10)) {
                cond = cr_bit(i.bi);
                if (!(i.bo & 0x08)) cond = "!" + cond;
            }
            if (i.lk) {
                line("if (%s) { u32 _tgt = cpu.lr; cpu.lr = 0x%xu; call_ppc(cpu, _tgt); }", cond.c_str(), i.pc + 4);
            } else {
                line("if (%s) return;", cond.c_str());  // conditional blr → conditional C return
            }
        }
        break;

    case PPCOp::BCCTR:
        if (i.lk) {                                     // bctrl — indirect call
            line("cpu.lr = 0x%xu;", i.pc + 4);
            line("call_ppc(cpu, cpu.ctr);");
        } else {                                        // bctr — computed/tail branch
            // If this is a jump table into THIS function, dispatch CTR to the in-function case
            // labels instead of handing off to Dolphin's JIT via tail_ppc (which corrupts
            // non-volatile regs across the recomp↔JIT boundary — the boot render crash). Genuine
            // external computed branches (e.g. a vtable tail call) fall through to tail_ppc.
            if (!ctx.jumptable_targets.empty()) {
                std::vector<u32> tgts(ctx.jumptable_targets.begin(), ctx.jumptable_targets.end());
                std::sort(tgts.begin(), tgts.end());
                line("switch (cpu.ctr) {");
                for (u32 t : tgts) line("case 0x%xu: goto lbl_%x;", t, t);
                line("default: tail_ppc(cpu, cpu.ctr); return;");
                line("}");
            } else {
                line("tail_ppc(cpu, cpu.ctr); return;");
            }
        }
        break;

    // ── SPR moves ───────────────────────────────────────────────────────────
    case PPCOp::MFSPR: {
        u16 spr = decode_spr(i.spr);
        switch (spr) {
        case SPR_LR:    line("%s = cpu.lr;",  d.c_str()); break;
        case SPR_CTR:   line("%s = cpu.ctr;", d.c_str()); break;
        case SPR_XER:   line("%s = (cpu.xer.so<<31)|(cpu.xer.ov<<30)|(cpu.xer.ca<<29)|cpu.xer.byte_count;", d.c_str()); break;
        case SPR_GQR0: case SPR_GQR0+1: case SPR_GQR0+2: case SPR_GQR0+3:
        case SPR_GQR0+4: case SPR_GQR0+5: case SPR_GQR0+6: case SPR_GQR0+7:
            line("%s = cpu.gqr[%d];", d.c_str(), spr - SPR_GQR0); break;
        case SPR_SRR0:  line("%s = cpu.srr0;", d.c_str()); break;
        case SPR_SRR1:  line("%s = cpu.srr1;", d.c_str()); break;
        default:
            // Storage-only SPR (see cpu_state.h): return what was written.
            line("%s = cpu.spr[%u];", d.c_str(), (unsigned)spr); break;
            // Not modeled in CPUState — read Dolphin's live SPR (HID0/HID2/BAT/...)
            line("%s = spr_get(%d);", d.c_str(), spr); break;
        }
        break;
    }
    case PPCOp::MTSPR: {
        u16 spr = decode_spr(i.spr);
        switch (spr) {
        case SPR_LR:    line("cpu.lr = %s;",  s.c_str()); break;
        case SPR_CTR:   line("cpu.ctr = %s;", s.c_str()); break;
        case SPR_XER:
            line("cpu.xer.so=((%s)>>31)&1; cpu.xer.ov=((%s)>>30)&1; cpu.xer.ca=((%s)>>29)&1; cpu.xer.byte_count=(%s)&0x7F;",
                 s.c_str(), s.c_str(), s.c_str(), s.c_str());
            break;
        case SPR_GQR0: case SPR_GQR0+1: case SPR_GQR0+2: case SPR_GQR0+3:
        case SPR_GQR0+4: case SPR_GQR0+5: case SPR_GQR0+6: case SPR_GQR0+7:
            line("cpu.gqr[%d] = %s;", spr - SPR_GQR0, s.c_str()); break;
        case SPR_SRR0:  line("cpu.srr0 = %s;", s.c_str()); break;
        case SPR_SRR1:  line("cpu.srr1 = %s;", s.c_str()); break;
        default:
            // Storage-only SPR (see cpu_state.h): inert on a PC, keep the value.
            line("cpu.spr[%u] = %s;", (unsigned)spr, s.c_str()); break;
            // Not modeled in CPUState — write Dolphin's live SPR (HID0/HID2/BAT/...)
            line("spr_set(%d, %s);", spr, s.c_str()); break;
        }
        break;
    }
    case PPCOp::MFCR:
        line("%s = cr_to_u32(cpu);", d.c_str());
        break;
    case PPCOp::MTCRF:
        line("u32_to_cr(cpu, %s, 0x%xu);", s.c_str(), (u32)i.crl_mask);
        break;

    // ── Load integer ────────────────────────────────────────────────────────
    case PPCOp::LWZ:  line("%s = MEM_R32(%s);", d.c_str(), ea(i).c_str()); break;
    case PPCOp::LWZU: line("%s = MEM_R32(%s); %s = %s;", d.c_str(), ea(i).c_str(), a.c_str(), ea(i).c_str()); break;
    case PPCOp::LWZX: line("%s = MEM_R32(%s);", d.c_str(), ea_x(i).c_str()); break;
    case PPCOp::LWZUX:line("%s = MEM_R32(%s); %s += %s;", d.c_str(), ea_x(i).c_str(), a.c_str(), b.c_str()); break;
    case PPCOp::LBZ:  line("%s = MEM_R8(%s);",  d.c_str(), ea(i).c_str()); break;
    case PPCOp::LBZU: line("%s = MEM_R8(%s);  %s = %s;", d.c_str(), ea(i).c_str(), a.c_str(), ea(i).c_str()); break;
    case PPCOp::LBZX: line("%s = MEM_R8(%s);",  d.c_str(), ea_x(i).c_str()); break;
    case PPCOp::LBZUX:line("%s = MEM_R8(%s);  %s += %s;", d.c_str(), ea_x(i).c_str(), a.c_str(), b.c_str()); break;
    case PPCOp::LHZ:  line("%s = MEM_R16(%s);", d.c_str(), ea(i).c_str()); break;
    case PPCOp::LHZU: line("%s = MEM_R16(%s); %s = %s;", d.c_str(), ea(i).c_str(), a.c_str(), ea(i).c_str()); break;
    case PPCOp::LHZX: line("%s = MEM_R16(%s);", d.c_str(), ea_x(i).c_str()); break;
    case PPCOp::LHA:   line("%s = (u32)(s32)(s16)MEM_R16(%s);", d.c_str(), ea(i).c_str()); break;
    case PPCOp::LHAU:  line("%s = (u32)(s32)(s16)MEM_R16(%s); %s = %s;", d.c_str(), ea(i).c_str(), a.c_str(), ea(i).c_str()); break;
    case PPCOp::LHAX:  line("%s = (u32)(s32)(s16)MEM_R16(%s);", d.c_str(), ea_x(i).c_str()); break;
    case PPCOp::LHAUX: line("%s = (u32)(s32)(s16)MEM_R16(%s); %s += %s;", d.c_str(), ea_x(i).c_str(), a.c_str(), b.c_str()); break;

    // ── Store integer ────────────────────────────────────────────────────────
    case PPCOp::STW:  line("MEM_W32(%s, %s);", ea(i).c_str(),   s.c_str()); break;
    case PPCOp::STWU: line("MEM_W32(%s, %s); %s = %s;", ea(i).c_str(), s.c_str(), a.c_str(), ea(i).c_str()); break;
    case PPCOp::STWX: line("MEM_W32(%s, %s);", ea_x(i).c_str(), s.c_str()); break;
    case PPCOp::STB:  line("MEM_W8(%s, (u8)%s);",  ea(i).c_str(),   s.c_str()); break;
    case PPCOp::STBU: line("MEM_W8(%s, (u8)%s);  %s = %s;", ea(i).c_str(), s.c_str(), a.c_str(), ea(i).c_str()); break;
    case PPCOp::STBX: line("MEM_W8(%s, (u8)%s);",  ea_x(i).c_str(), s.c_str()); break;
    case PPCOp::STH:  line("MEM_W16(%s, (u16)%s);", ea(i).c_str(),  s.c_str()); break;
    case PPCOp::STHU: line("MEM_W16(%s, (u16)%s); %s = %s;", ea(i).c_str(), s.c_str(), a.c_str(), ea(i).c_str()); break;
    case PPCOp::STHX: line("MEM_W16(%s, (u16)%s);", ea_x(i).c_str(), s.c_str()); break;

    // ── Load/store FP ────────────────────────────────────────────────────────
    case PPCOp::LFS:
        line("%s = MEM_RF32(%s);", fd.c_str(), ea(i).c_str());
        line("cpu.fpr[%d].ps1 = cpu.fpr[%d].ps0;", i.rD, i.rD);  // GC loads ps1=ps0
        break;
    case PPCOp::LFSU:
        line("%s = MEM_RF32(%s); %s = %s;", fd.c_str(), ea(i).c_str(), a.c_str(), ea(i).c_str());
        break;
    case PPCOp::LFSX:
        line("%s = MEM_RF32(%s);", fd.c_str(), ea_x(i).c_str());
        break;
    case PPCOp::LFD:
        line("%s = MEM_RF64(%s);", fd.c_str(), ea(i).c_str());
        break;
    case PPCOp::LFDU:
        line("%s = MEM_RF64(%s); %s = %s;", fd.c_str(), ea(i).c_str(), a.c_str(), ea(i).c_str());
        break;
    case PPCOp::LFDX:
        line("%s = MEM_RF64(%s);", fd.c_str(), ea_x(i).c_str());
        break;
    case PPCOp::STFS:
        line("MEM_WF32(%s, (f32)%s);", ea(i).c_str(), fd.c_str());
        break;
    case PPCOp::STFSU:
        line("MEM_WF32(%s, (f32)%s); %s = %s;", ea(i).c_str(), fd.c_str(), a.c_str(), ea(i).c_str());
        break;
    case PPCOp::STFSX:
        line("MEM_WF32(%s, (f32)%s);", ea_x(i).c_str(), fd.c_str());
        break;
    case PPCOp::STFD:
        line("MEM_WF64(%s, %s);", ea(i).c_str(), fd.c_str());
        break;
    case PPCOp::STFDU:
        line("MEM_WF64(%s, %s); %s = %s;", ea(i).c_str(), fd.c_str(), a.c_str(), ea(i).c_str());
        break;
    case PPCOp::STFDX:
        line("MEM_WF64(%s, %s);", ea_x(i).c_str(), fd.c_str());
        break;
    case PPCOp::STFIWX:
        line("MEM_W32(%s, (u32)(u64)%s);", ea_x(i).c_str(), fd.c_str());
        break;

    // ── FP arithmetic ────────────────────────────────────────────────────────
    case PPCOp::FADD:  line("%s = %s + %s;", fd.c_str(), fa.c_str(), fb.c_str()); break;
    case PPCOp::FSUB:  line("%s = %s - %s;", fd.c_str(), fa.c_str(), fb.c_str()); break;
    case PPCOp::FMUL:  line("%s = %s * %s;", fd.c_str(), fa.c_str(), fc.c_str()); break;
    case PPCOp::FDIV:  line("%s = %s / %s;", fd.c_str(), fa.c_str(), fb.c_str()); break;
    // Single-precision scalar FP ops BROADCAST the result to BOTH paired slots (ps1=ps0) on
    // Gekko — Dolphin's `ps[FD].Fill(result)` (see Interpreter_FloatingPoint.cpp: "PS1 must be set
    // to the value of PS0 or DragonballZ will be f**ked up"). Emitting ps0 only left ps1 stale, so
    // any later paired use of ps1 read garbage — the every-other-pixel comb in the THP paired-single
    // IDCT (and the skinned-model distortion). Double-precision ops below leave ps1 unchanged.
    case PPCOp::FADDS: line("%s = (f32)(%s + %s); %s = %s;", fd.c_str(), fa.c_str(), fb.c_str(), psd1.c_str(), psd0.c_str()); break;
    case PPCOp::FSUBS: line("%s = (f32)(%s - %s); %s = %s;", fd.c_str(), fa.c_str(), fb.c_str(), psd1.c_str(), psd0.c_str()); break;
    case PPCOp::FMULS: line("%s = (f32)(%s * %s); %s = %s;", fd.c_str(), fa.c_str(), fc.c_str(), psd1.c_str(), psd0.c_str()); break;
    case PPCOp::FDIVS: line("%s = (f32)(%s / %s); %s = %s;", fd.c_str(), fa.c_str(), fb.c_str(), psd1.c_str(), psd0.c_str()); break;
    // Gekko's madd family is a true fused multiply-add (single rounding), matching
    // Dolphin's std::fma(). Emitting a*c+b would round twice and diverge.
    case PPCOp::FMADD: line("%s = std::fma(%s, %s, %s);", fd.c_str(), fa.c_str(), fc.c_str(), fb.c_str()); break;
    case PPCOp::FMSUB: line("%s = std::fma(%s, %s, -(%s));", fd.c_str(), fa.c_str(), fc.c_str(), fb.c_str()); break;
    case PPCOp::FNMADD:line("%s = -std::fma(%s, %s, %s);", fd.c_str(), fa.c_str(), fc.c_str(), fb.c_str()); break;
    case PPCOp::FNMSUB:line("%s = -std::fma(%s, %s, -(%s));", fd.c_str(), fa.c_str(), fc.c_str(), fb.c_str()); break;
    case PPCOp::FMADDS:line("%s = (f32)std::fma(%s, %s, %s); %s = %s;", fd.c_str(), fa.c_str(), fc.c_str(), fb.c_str(), psd1.c_str(), psd0.c_str()); break;
    case PPCOp::FMSUBS:line("%s = (f32)std::fma(%s, %s, -(%s)); %s = %s;", fd.c_str(), fa.c_str(), fc.c_str(), fb.c_str(), psd1.c_str(), psd0.c_str()); break;
    case PPCOp::FNMADDS:line("%s = (f32)(-std::fma(%s, %s, %s)); %s = %s;", fd.c_str(), fa.c_str(), fc.c_str(), fb.c_str(), psd1.c_str(), psd0.c_str()); break;
    case PPCOp::FNMSUBS:line("%s = (f32)(-std::fma(%s, %s, -(%s))); %s = %s;", fd.c_str(), fa.c_str(), fc.c_str(), fb.c_str(), psd1.c_str(), psd0.c_str()); break;
    case PPCOp::FABS:  line("%s = std::abs(%s);", fd.c_str(), fb.c_str()); break;
    case PPCOp::FNABS: line("%s = -std::abs(%s);", fd.c_str(), fb.c_str()); break;
    case PPCOp::FNEG:  line("%s = -%s;", fd.c_str(), fb.c_str()); break;
    case PPCOp::FMR:   line("%s = %s;", fd.c_str(), fb.c_str()); break;
    case PPCOp::FRSP:  line("%s = (f32)%s; %s = %s;", fd.c_str(), fb.c_str(), psd1.c_str(), psd0.c_str()); break;
    case PPCOp::FCTIW: line("%s = std::bit_cast<f64>((u64)(u32)(s32)%s);", fd.c_str(), fb.c_str()); break;
    case PPCOp::FCTIWZ:line("%s = std::bit_cast<f64>((u64)(u32)(s32)%s);", fd.c_str(), fb.c_str()); break;
    case PPCOp::FRES:  line("%s = fres(%s); %s = %s;", fd.c_str(), fb.c_str(), psd1.c_str(), psd0.c_str()); break;
    case PPCOp::FRSQRTE:line("%s = frsqrte(%s);", fd.c_str(), fb.c_str()); break;  // double-est: ps0 only (Dolphin SetPS0)
    case PPCOp::FRESS: line("%s = (f32)fres(%s); %s = %s;", fd.c_str(), fb.c_str(), psd1.c_str(), psd0.c_str()); break;
    case PPCOp::FSEL:
        line("%s = (%s >= 0.0) ? %s : %s;", fd.c_str(), fa.c_str(), fc.c_str(), fb.c_str());
        break;
    case PPCOp::FCMPU:
        // The CR field's bit-3 (the .so slot) is the FU "unordered" flag for FP
        // compares — set when either operand is NaN (not hardcoded 0). A wrong FU
        // sends bun/bns branches the wrong way (found via the diff harness: atan2f
        // returned Inf instead of NaN).
        line("{ double _a=%s,_b=%s; cpu.cr[%d].lt=_a<_b; cpu.cr[%d].gt=_a>_b; cpu.cr[%d].eq=_a==_b; cpu.cr[%d].so=(std::isnan(_a)||std::isnan(_b)); }",
             fa.c_str(), fb.c_str(), i.crfD, i.crfD, i.crfD, i.crfD);
        break;
    case PPCOp::FCMPO:  // ordered compare — same result as FCMPU for our purposes
        line("{ double _a=%s,_b=%s; cpu.cr[%d].lt=_a<_b; cpu.cr[%d].gt=_a>_b; cpu.cr[%d].eq=_a==_b; cpu.cr[%d].so=(std::isnan(_a)||std::isnan(_b)); }",
             fa.c_str(), fb.c_str(), i.crfD, i.crfD, i.crfD, i.crfD);
        break;

    // ── Paired singles ───────────────────────────────────────────────────────
    case PPCOp::PS_ADD:
        // Every Gekko PS arithmetic result is rounded to SINGLE. single+single is
        // exact in double, so (f32)(a+b) is the one correct rounding.
        line("%s = (f32)(%s + %s);", psd0.c_str(), psa0.c_str(), psb0.c_str());
        line("%s = (f32)(%s + %s);", psd1.c_str(), psa1.c_str(), psb1.c_str());
        break;
    case PPCOp::PS_SUB:
        line("%s = (f32)(%s - %s);", psd0.c_str(), psa0.c_str(), psb0.c_str());
        line("%s = (f32)(%s - %s);", psd1.c_str(), psa1.c_str(), psb1.c_str());
        break;
    case PPCOp::PS_MUL:
        line("%s = (f32)(%s * %s);", psd0.c_str(), psa0.c_str(), psc0.c_str());
        line("%s = (f32)(%s * %s);", psd1.c_str(), psa1.c_str(), psc1.c_str());
        break;
    case PPCOp::PS_DIV:
        // single-rounded float division (a (f32) cast of the double quotient would
        // double-round)
        line("%s = (f32)%s / (f32)%s;", psd0.c_str(), psa0.c_str(), psb0.c_str());
        line("%s = (f32)%s / (f32)%s;", psd1.c_str(), psa1.c_str(), psb1.c_str());
        break;
    case PPCOp::PS_MADD:
        // FUSED like fmadds, then rounded to single (was a*c+b in double, unfused
        // and unrounded — caught by the PSMTXConcat native-port shadow harness:
        // 1-ULP divergences vs the fused hardware order)
        line("%s = (f32)std::fma(%s, %s, %s);", psd0.c_str(), psa0.c_str(), psc0.c_str(), psb0.c_str());
        line("%s = (f32)std::fma(%s, %s, %s);", psd1.c_str(), psa1.c_str(), psc1.c_str(), psb1.c_str());
        break;
    case PPCOp::PS_MSUB:
        line("%s = (f32)std::fma(%s, %s, -%s);", psd0.c_str(), psa0.c_str(), psc0.c_str(), psb0.c_str());
        line("%s = (f32)std::fma(%s, %s, -%s);", psd1.c_str(), psa1.c_str(), psc1.c_str(), psb1.c_str());
        break;
    case PPCOp::PS_NMADD:
        line("%s = -(f32)std::fma(%s, %s, %s);", psd0.c_str(), psa0.c_str(), psc0.c_str(), psb0.c_str());
        line("%s = -(f32)std::fma(%s, %s, %s);", psd1.c_str(), psa1.c_str(), psc1.c_str(), psb1.c_str());
        break;
    case PPCOp::PS_NMSUB:
        line("%s = -(f32)std::fma(%s, %s, -%s);", psd0.c_str(), psa0.c_str(), psc0.c_str(), psb0.c_str());
        line("%s = -(f32)std::fma(%s, %s, -%s);", psd1.c_str(), psa1.c_str(), psc1.c_str(), psb1.c_str());
        break;
    case PPCOp::PS_NEG:
        line("%s = -%s;", psd0.c_str(), psb0.c_str());
        line("%s = -%s;", psd1.c_str(), psb1.c_str());
        break;
    case PPCOp::PS_ABS:
        line("%s = std::abs(%s);", psd0.c_str(), psb0.c_str());
        line("%s = std::abs(%s);", psd1.c_str(), psb1.c_str());
        break;
    case PPCOp::PS_NABS:
        line("%s = -std::abs(%s);", psd0.c_str(), psb0.c_str());
        line("%s = -std::abs(%s);", psd1.c_str(), psb1.c_str());
        break;
    case PPCOp::PS_MR:
        line("%s = %s;", psd0.c_str(), psb0.c_str());
        line("%s = %s;", psd1.c_str(), psb1.c_str());
        break;
    case PPCOp::PS_SUM0:
        line("%s = (f32)(%s + %s);", psd0.c_str(), psa0.c_str(), psb1.c_str());
        line("%s = %s;",      psd1.c_str(), psc1.c_str());
        break;
    case PPCOp::PS_SUM1:
        line("%s = %s;",      psd0.c_str(), psc0.c_str());
        line("%s = (f32)(%s + %s);", psd1.c_str(), psa0.c_str(), psb0.c_str());
        break;
    case PPCOp::PS_MULS0:  // fD.ps0 = fA.ps0 * fC.ps0; fD.ps1 = fA.ps1 * fC.ps0
        line("%s = (f32)(%s * %s);", psd0.c_str(), psa0.c_str(), psc0.c_str());
        line("%s = (f32)(%s * %s);", psd1.c_str(), psa1.c_str(), psc0.c_str());
        break;
    case PPCOp::PS_MULS1:  // fD.ps0 = fA.ps0 * fC.ps1; fD.ps1 = fA.ps1 * fC.ps1
        line("%s = (f32)(%s * %s);", psd0.c_str(), psa0.c_str(), psc1.c_str());
        line("%s = (f32)(%s * %s);", psd1.c_str(), psa1.c_str(), psc1.c_str());
        break;
    case PPCOp::PS_MADDS0: // fD.ps0 = fA.ps0*fC.ps0 + fB.ps0; fD.ps1 = fA.ps1*fC.ps0 + fB.ps1
        line("%s = (f32)std::fma(%s, %s, %s);", psd0.c_str(), psa0.c_str(), psc0.c_str(), psb0.c_str());
        line("%s = (f32)std::fma(%s, %s, %s);", psd1.c_str(), psa1.c_str(), psc0.c_str(), psb1.c_str());
        break;
    case PPCOp::PS_MADDS1: // fD.ps0 = fA.ps0*fC.ps1 + fB.ps0; fD.ps1 = fA.ps1*fC.ps1 + fB.ps1
        line("%s = (f32)std::fma(%s, %s, %s);", psd0.c_str(), psa0.c_str(), psc1.c_str(), psb0.c_str());
        line("%s = (f32)std::fma(%s, %s, %s);", psd1.c_str(), psa1.c_str(), psc1.c_str(), psb1.c_str());
        break;
    case PPCOp::PS_SEL:
        line("%s = (%s >= 0.0) ? %s : %s;", psd0.c_str(), psa0.c_str(), psc0.c_str(), psb0.c_str());
        line("%s = (%s >= 0.0) ? %s : %s;", psd1.c_str(), psa1.c_str(), psc1.c_str(), psb1.c_str());
        break;
    case PPCOp::PS_RES:
        line("%s = fres(%s);", psd0.c_str(), psb0.c_str());
        line("%s = fres(%s);", psd1.c_str(), psb1.c_str());
        break;
    case PPCOp::PS_RSQRTE:
        line("%s = frsqrte(%s);", psd0.c_str(), psb0.c_str());
        line("%s = frsqrte(%s);", psd1.c_str(), psb1.c_str());
        break;
    // ps_mergeXY: fD.ps0 = fA.psX, fD.ps1 = fB.psY. Read both sources into temps
    // first — rD may alias rA or rB, and the previous ps_merge00 also took ps1
    // from fA instead of fB.
    case PPCOp::PS_MERGE00:
        line("{ f64 _a=%s,_b=%s; %s=_a; %s=_b; }", psa0.c_str(), psb0.c_str(), psd0.c_str(), psd1.c_str());
        break;
    case PPCOp::PS_MERGE01:
        line("{ f64 _a=%s,_b=%s; %s=_a; %s=_b; }", psa0.c_str(), psb1.c_str(), psd0.c_str(), psd1.c_str());
        break;
    case PPCOp::PS_MERGE10:
        line("{ f64 _a=%s,_b=%s; %s=_a; %s=_b; }", psa1.c_str(), psb0.c_str(), psd0.c_str(), psd1.c_str());
        break;
    case PPCOp::PS_MERGE11:
        line("{ f64 _a=%s,_b=%s; %s=_a; %s=_b; }", psa1.c_str(), psb1.c_str(), psd0.c_str(), psd1.c_str());
        break;

    // ── psq_l / psq_st ───────────────────────────────────────────────────────
    // psq_load/psq_store do the type-correct element width + stride (1/2/4 bytes). Emitting
    // MEM_R32(ea)/MEM_R32(ea+4) here was only valid for float; quantized types (u8/s8/u16/s16)
    // need a narrow, correctly-strided access. See runtime/memory_bridge.cpp.
    case PPCOp::PSQ_L:
        line("psq_load(%s, cpu.gqr[%d], %d, &%s, &%s);", ea(i).c_str(), i.i_gqr, i.w, psd0.c_str(), psd1.c_str());
        break;
    case PPCOp::PSQ_LU: {
        std::string addr = ea(i);
        line("{ u32 _ea=%s; psq_load(_ea, cpu.gqr[%d], %d, &%s, &%s); %s = _ea; }",
             addr.c_str(), i.i_gqr, i.w, psd0.c_str(), psd1.c_str(), a.c_str());
        break;
    }
    case PPCOp::PSQ_ST:
        line("psq_store(%s, cpu.gqr[%d], %d, %s, %s);", ea(i).c_str(), i.i_gqr, i.w, psd0.c_str(), psd1.c_str());
        break;
    case PPCOp::PSQ_STU: {
        std::string addr = ea(i);
        line("{ u32 _ea=%s; psq_store(_ea, cpu.gqr[%d], %d, %s, %s); %s = _ea; }",
             addr.c_str(), i.i_gqr, i.w, psd0.c_str(), psd1.c_str(), a.c_str());
        break;
    }

    // ── CR logic ─────────────────────────────────────────────────────────────
    case PPCOp::CRAND: line("%s = %s & %s;",  cr_bit(i.rD).c_str(), cr_bit(i.rA).c_str(), cr_bit(i.rB).c_str()); break;
    case PPCOp::CRANDC:line("%s = %s & !%s;", cr_bit(i.rD).c_str(), cr_bit(i.rA).c_str(), cr_bit(i.rB).c_str()); break;
    case PPCOp::CROR:  line("%s = %s | %s;",  cr_bit(i.rD).c_str(), cr_bit(i.rA).c_str(), cr_bit(i.rB).c_str()); break;
    case PPCOp::CRORC: line("%s = %s | !%s;", cr_bit(i.rD).c_str(), cr_bit(i.rA).c_str(), cr_bit(i.rB).c_str()); break;
    case PPCOp::CRXOR: line("%s = %s ^ %s;",  cr_bit(i.rD).c_str(), cr_bit(i.rA).c_str(), cr_bit(i.rB).c_str()); break;
    case PPCOp::CRNOR: line("%s = !(%s | %s);",  cr_bit(i.rD).c_str(), cr_bit(i.rA).c_str(), cr_bit(i.rB).c_str()); break;
    case PPCOp::CRNAND:line("%s = !(%s & %s);", cr_bit(i.rD).c_str(), cr_bit(i.rA).c_str(), cr_bit(i.rB).c_str()); break;
    case PPCOp::CREQV: line("%s = !(%s ^ %s);", cr_bit(i.rD).c_str(), cr_bit(i.rA).c_str(), cr_bit(i.rB).c_str()); break;
    case PPCOp::MCRF:
        line("cpu.cr[%d] = cpu.cr[%d];", i.crfD, i.crfS);
        break;

    // ── System / cache (mostly no-ops in recomp) ────────────────────────────
    case PPCOp::SC:
        line("os_hle_call(cpu, 0x%xu);", i.pc);
        break;
    case PPCOp::SYNC: case PPCOp::ISYNC: case PPCOp::EIEIO:
    case PPCOp::DCBT: case PPCOp::DCBTST: case PPCOp::DCBF:
    case PPCOp::DCBI:
    case PPCOp::DCBST: case PPCOp::TLBIE: case PPCOp::TLBSYNC:
        line("// %s — no-op in recomp", i.mnemonic().c_str());
        break;
    // icbi is NOT a no-op: recomp execution never fetches through Dolphin's instruction cache,
    // but the INTERPRETER (hybrid paths: thread bodies, native interrupt handlers, run_jit_sync)
    // does. Game code that loads/copies code under recomp and then ICInvalidateRange's it must
    // invalidate Dolphin's icache too, or the interpreter later fetches the stale pre-copy line
    // (caught live: fetched=4800302d vs ram=7c800038 at 803378a8 — a phantom `bl` into the middle
    // of a printf helper -> blr through a never-written LR slot -> JUT crash screen, 2026-06-10).
    case PPCOp::ICBI:
        line("icbi32(%s);", ea_x(i).c_str());
        break;
    // dcbz is NOT a no-op: it zeroes the 32-byte cache block containing EA (no memory read).
    // SMS's THP decoder uses it to clear the DCT coefficient buffer before the VLC decoder fills
    // the non-zero coefficients; NOP'ing it left stale data → the per-MCU comb in the FMV.
    case PPCOp::DCBZ:
        line("dcbz32(%s);", ea_x(i).c_str());
        break;

    case PPCOp::MFMSR: line("%s = msr_get(); // live MSR from Dolphin", d.c_str()); break;
    case PPCOp::MFSR:  line("%s = 0; // MFSR: segment registers not emulated", d.c_str()); break;
    case PPCOp::MFSRIN:line("%s = 0; // MFSRIN: segment registers not emulated", d.c_str()); break;
    // MTMSR: set the modeled MSR without a synchronous exception check (delivery is deferred to a
    // recomp→JIT boundary — matches the OSDisableInterrupts hazard fix; never deliver mid-tree).
    case PPCOp::MTMSR: line("msr_set_raw(%s);", s.c_str()); break;
    // RFI (exception return / OS context switch): restore MSR from SRR1, branch to SRR0. The
    // function ends here — tail-branch to the resumed PC (recomp target → nested call; else handoff).
    case PPCOp::RFI:
        line("msr_set_raw(cpu.srr1);");
        line("tail_ppc(cpu, cpu.srr0 & ~3u);");
        line("return;");
        break;
    // Segment/TLB writes still have HW side effects we can't reproduce — function_needs_jit keeps
    // those functions in Dolphin; these emits are belt-and-suspenders.

    // ── lmw / stmw ────────────────────────────────────────────────────────────
    // Load/store multiple: rD..r31 from consecutive words starting at EA
    case PPCOp::LMW:
        line("{ u32 _ea = %s;", ea(i).c_str());
        for (int r = i.rD; r <= 31; r++)
            line("  cpu.gpr[%d] = MEM_R32(_ea + %d);", r, (r - i.rD) * 4);
        line("}");
        break;
    case PPCOp::STMW:
        line("{ u32 _ea = %s;", ea(i).c_str());
        for (int r = i.rS; r <= 31; r++)
            line("  MEM_W32(_ea + %d, cpu.gpr[%d]);", (r - i.rS) * 4, r);
        line("}");
        break;

    // ── mftb (time base) ──────────────────────────────────────────────────────
    case PPCOp::MFTB: {
        // The TBR number is split-encoded in the SPR field (268=TBL, 269=TBU),
        // exactly like mfspr. Read Dolphin's live 64-bit time base so spin/delay
        // loops that wait for the clock to advance actually terminate.
        u16 tbr = decode_spr(i.spr);
        if (tbr == 269)          // TBU (upper 32)
            line("%s = (u32)(tb_get() >> 32);", d.c_str());
        else                      // TBL (lower 32)
            line("%s = (u32)tb_get();", d.c_str());
        break;
    }

    // ── FPSCR ops ─────────────────────────────────────────────────────────────
    case PPCOp::MFFS:
        line("%s = std::bit_cast<f64>((u64)cpu.fpscr);", fd.c_str());
        if (i.rc) line("update_cr1(cpu);");
        break;
    case PPCOp::MTFSF:
        line("{ u32 _v=(u32)(u64)std::bit_cast<u64>(%s); cpu.fpscr=(_v&0x%xu)|(cpu.fpscr&~0x%xu); }",
             fd.c_str(), (u32)i.fm << 8, (u32)i.fm << 8);
        break;
    case PPCOp::MTFSB0:
        line("cpu.fpscr &= ~(1u << (31 - %d));", i.rD);
        break;
    case PPCOp::MTFSB1:
        line("cpu.fpscr |= (1u << (31 - %d));", i.rD);
        break;
    case PPCOp::MTFSFI:
        line("cpu.fpscr = (cpu.fpscr & ~(0xFu << (28 - %d*4))) | (%uu << (28 - %d*4));",
             i.crfD, i.wi, i.crfD);
        break;

    // ── PS compare ────────────────────────────────────────────────────────────
    case PPCOp::PS_CMPU0:
    case PPCOp::PS_CMPO0:
        line("{ double _a=%s,_b=%s; cpu.cr[%d].lt=_a<_b; cpu.cr[%d].gt=_a>_b; cpu.cr[%d].eq=_a==_b; cpu.cr[%d].so=0; }",
             psa0.c_str(), psb0.c_str(), i.crfD, i.crfD, i.crfD, i.crfD);
        break;
    case PPCOp::PS_CMPU1:
    case PPCOp::PS_CMPO1:
        line("{ double _a=%s,_b=%s; cpu.cr[%d].lt=_a<_b; cpu.cr[%d].gt=_a>_b; cpu.cr[%d].eq=_a==_b; cpu.cr[%d].so=0; }",
             psa1.c_str(), psb1.c_str(), i.crfD, i.crfD, i.crfD, i.crfD);
        break;

    // ── psq_lx / psq_stx (indexed PS quantized) ──────────────────────────────
    case PPCOp::PSQ_LX:
        line("psq_load(%s, cpu.gqr[%d], %d, &%s, &%s);", ea_x(i).c_str(), i.i_gqr, i.w, psd0.c_str(), psd1.c_str());
        break;
    case PPCOp::PSQ_STX:
        line("psq_store(%s, cpu.gqr[%d], %d, %s, %s);", ea_x(i).c_str(), i.i_gqr, i.w, psd0.c_str(), psd1.c_str());
        break;

    // ── Unhandled ────────────────────────────────────────────────────────────
    default:
        // A comment alone would make an unhandled opcode a SILENT no-op: execution
        // continues with the instruction's effect simply missing, and the corruption
        // surfaces somewhere unrelated. In the Dolphin era the JIT covered these; a
        // standalone port has no fallback, so it has to stop at the real cause.
        line("// UNHANDLED: %s at 0x%08x (raw=0x%08x)", i.mnemonic().c_str(), i.pc, i.raw);
        line("rt_unhandled_insn(cpu, 0x%08xu, 0x%08xu, \"%s\");", i.pc, i.raw,
             i.mnemonic().c_str());
        unhandled_++;
        unhandled_ops_.push_back(i.mnemonic());
        break;
    }
}

// Linear scan to find function boundaries.
// Heuristic: BL target = new function start; BCLR with bo=0x14 = function end.
std::vector<u32> find_call_targets(const u8* text, u32 base_addr, u32 size) {
    std::vector<u32> targets;
    for (u32 off = 0; off + 4 <= size; off += 4) {
        u32 word_be;
        std::memcpy(&word_be, text + off, 4);
        u32 word = __builtin_bswap32(word_be);  // ROM is big-endian
        u32 pc   = base_addr + off;
        PPCInstr instr = decode(word, pc);

        // bl / bcl → the callee starts at the branch target, wherever it lives.
        if ((instr.op == PPCOp::B || instr.op == PPCOp::BC) && instr.lk)
            targets.push_back(instr.target);
    }
    std::sort(targets.begin(), targets.end());
    targets.erase(std::unique(targets.begin(), targets.end()), targets.end());
    return targets;
}

std::vector<u32> find_functions(const u8* text, u32 base_addr, u32 size) {
    std::vector<u32> funcs;
    funcs.push_back(base_addr);  // section start is a function start by definition
    for (u32 t : find_call_targets(text, base_addr, size))
        if (t >= base_addr && t < base_addr + size) funcs.push_back(t);

    std::sort(funcs.begin(), funcs.end());
    funcs.erase(std::unique(funcs.begin(), funcs.end()), funcs.end());
    return funcs;
}
