#include "ppc_decoder.h"

// Human-readable mnemonic for each PPCOp — used in analysis output and error messages.
std::string PPCInstr::mnemonic() const {
    switch (op) {
    case PPCOp::ADD:    return rc ? "add."   : "add";
    case PPCOp::ADDO:   return rc ? "addo."  : "addo";
    case PPCOp::ADDI:   return rA == 0 ? "li" : "addi";
    case PPCOp::ADDIS:  return rA == 0 ? "lis" : "addis";
    case PPCOp::ADDC:   return rc ? "addc."  : "addc";
    case PPCOp::ADDE:   return rc ? "adde."  : "adde";
    case PPCOp::ADDME:  return rc ? "addme." : "addme";
    case PPCOp::ADDZE:  return rc ? "addze." : "addze";
    case PPCOp::SUBF:   return rc ? "subf."  : "subf";
    case PPCOp::SUBFC:  return rc ? "subfc." : "subfc";
    case PPCOp::SUBFE:  return rc ? "subfe." : "subfe";
    case PPCOp::SUBFIC: return "subfic";
    case PPCOp::SUBFZE: return rc ? "subfze." : "subfze";
    case PPCOp::SUBFME: return rc ? "subfme." : "subfme";
    case PPCOp::NEG:    return rc ? "neg."   : "neg";
    case PPCOp::MULLI:  return "mulli";
    case PPCOp::MULLW:  return rc ? "mullw." : "mullw";
    case PPCOp::MULHW:  return rc ? "mulhw." : "mulhw";
    case PPCOp::MULHWU: return rc ? "mulhwu.": "mulhwu";
    case PPCOp::DIVW:   return rc ? "divw."  : "divw";
    case PPCOp::DIVWU:  return rc ? "divwu." : "divwu";
    case PPCOp::CMP:    return "cmp";
    case PPCOp::CMPI:   return "cmpi";
    case PPCOp::CMPL:   return "cmpl";
    case PPCOp::CMPLI:  return "cmpli";
    case PPCOp::AND:    return rc ? "and."   : "and";
    case PPCOp::ANDI_DOT:  return "andi.";
    case PPCOp::ANDIS_DOT: return "andis.";
    case PPCOp::ANDC:   return rc ? "andc."  : "andc";
    case PPCOp::OR:     return rc ? "or."    : "or";
    case PPCOp::ORI:    return "ori";
    case PPCOp::ORIS:   return "oris";
    case PPCOp::ORC:    return rc ? "orc."   : "orc";
    case PPCOp::XOR:    return rc ? "xor."   : "xor";
    case PPCOp::XORI:   return "xori";
    case PPCOp::XORIS:  return "xoris";
    case PPCOp::NOR:    return rc ? "nor."   : "nor";
    case PPCOp::NAND:   return rc ? "nand."  : "nand";
    case PPCOp::EQV:    return rc ? "eqv."   : "eqv";
    case PPCOp::EXTSB:  return rc ? "extsb." : "extsb";
    case PPCOp::EXTSH:  return rc ? "extsh." : "extsh";
    case PPCOp::CNTLZW: return rc ? "cntlzw.": "cntlzw";
    case PPCOp::RLWINM: return rc ? "rlwinm.": "rlwinm";
    case PPCOp::RLWIMI: return rc ? "rlwimi.": "rlwimi";
    case PPCOp::RLWNM:  return rc ? "rlwnm." : "rlwnm";
    case PPCOp::SLW:    return rc ? "slw."   : "slw";
    case PPCOp::SRW:    return rc ? "srw."   : "srw";
    case PPCOp::SRAW:   return rc ? "sraw."  : "sraw";
    case PPCOp::SRAWI:  return rc ? "srawi." : "srawi";
    case PPCOp::B:      return lk ? (aa ? "bla" : "bl") : (aa ? "ba" : "b");
    case PPCOp::BC:     return lk ? "bcl"   : "bc";
    case PPCOp::BCLR:   return lk ? "bclrl" : (bo==0x14 ? "blr" : "bclr");
    case PPCOp::BCCTR:  return lk ? "bcctrl": (bo==0x14 ? "bctr" : "bcctr");
    case PPCOp::CRAND:  return "crand";
    case PPCOp::CRANDC: return "crandc";
    case PPCOp::CROR:   return "cror";
    case PPCOp::CRORC:  return "crorc";
    case PPCOp::CRXOR:  return "crxor";
    case PPCOp::CRNOR:  return "crnor";
    case PPCOp::CRNAND: return "crnand";
    case PPCOp::CREQV:  return "creqv";
    case PPCOp::MCRF:   return "mcrf";
    case PPCOp::MFSPR:  return "mfspr";
    case PPCOp::MTSPR:  return "mtspr";
    case PPCOp::MFCR:   return "mfcr";
    case PPCOp::MTCRF:  return "mtcrf";
    case PPCOp::MTMSR:  return "mtmsr";
    case PPCOp::MFTB:   return "mftb";
    case PPCOp::LWZ:    return "lwz";
    case PPCOp::LWZU:   return "lwzu";
    case PPCOp::LWZX:   return "lwzx";
    case PPCOp::LWZUX:  return "lwzux";
    case PPCOp::LBZ:    return "lbz";
    case PPCOp::LBZU:   return "lbzu";
    case PPCOp::LBZX:   return "lbzx";
    case PPCOp::LBZUX:  return "lbzux";
    case PPCOp::LHZ:    return "lhz";
    case PPCOp::LHZU:   return "lhzu";
    case PPCOp::LHZX:   return "lhzx";
    case PPCOp::LHA:    return "lha";
    case PPCOp::LHAU:   return "lhau";
    case PPCOp::LHAUX:  return "lhaux";
    case PPCOp::LHAX:   return "lhax";
    case PPCOp::LMW:    return "lmw";
    case PPCOp::STW:    return "stw";
    case PPCOp::STWU:   return "stwu";
    case PPCOp::STWX:   return "stwx";
    case PPCOp::STWUX:  return "stwux";
    case PPCOp::STB:    return "stb";
    case PPCOp::STBU:   return "stbu";
    case PPCOp::STBX:   return "stbx";
    case PPCOp::STBUX:  return "stbux";
    case PPCOp::STH:    return "sth";
    case PPCOp::STHU:   return "sthu";
    case PPCOp::STHX:   return "sthx";
    case PPCOp::STMW:   return "stmw";
    case PPCOp::LFS:    return "lfs";
    case PPCOp::LFSU:   return "lfsu";
    case PPCOp::LFSX:   return "lfsx";
    case PPCOp::LFD:    return "lfd";
    case PPCOp::LFDU:   return "lfdu";
    case PPCOp::LFDX:   return "lfdx";
    case PPCOp::STFS:   return "stfs";
    case PPCOp::STFSU:  return "stfsu";
    case PPCOp::STFSX:  return "stfsx";
    case PPCOp::STFD:   return "stfd";
    case PPCOp::STFDU:  return "stfdu";
    case PPCOp::STFDX:  return "stfdx";
    case PPCOp::STFIWX: return "stfiwx";
    case PPCOp::FADD:   return rc ? "fadd."  : "fadd";
    case PPCOp::FSUB:   return rc ? "fsub."  : "fsub";
    case PPCOp::FMUL:   return rc ? "fmul."  : "fmul";
    case PPCOp::FDIV:   return rc ? "fdiv."  : "fdiv";
    case PPCOp::FADDS:  return rc ? "fadds." : "fadds";
    case PPCOp::FSUBS:  return rc ? "fsubs." : "fsubs";
    case PPCOp::FMULS:  return rc ? "fmuls." : "fmuls";
    case PPCOp::FDIVS:  return rc ? "fdivs." : "fdivs";
    case PPCOp::FMADD:  return rc ? "fmadd." : "fmadd";
    case PPCOp::FMSUB:  return rc ? "fmsub." : "fmsub";
    case PPCOp::FNMADD: return rc ? "fnmadd.": "fnmadd";
    case PPCOp::FNMSUB: return rc ? "fnmsub.": "fnmsub";
    case PPCOp::FMADDS: return "fmadds";
    case PPCOp::FMSUBS: return "fmsubs";
    case PPCOp::FNMADDS:return "fnmadds";
    case PPCOp::FNMSUBS:return "fnmsubs";
    case PPCOp::FABS:   return rc ? "fabs."  : "fabs";
    case PPCOp::FNABS:  return rc ? "fnabs." : "fnabs";
    case PPCOp::FNEG:   return rc ? "fneg."  : "fneg";
    case PPCOp::FMR:    return rc ? "fmr."   : "fmr";
    case PPCOp::FRSP:   return rc ? "frsp."  : "frsp";
    case PPCOp::FCTIW:  return "fctiw";
    case PPCOp::FCTIWZ: return "fctiwz";
    case PPCOp::FCMPU:  return "fcmpu";
    case PPCOp::FCMPO:  return "fcmpo";
    case PPCOp::FRES:   return "fres";
    case PPCOp::FRSQRTE:return "frsqrte";
    case PPCOp::FRESS:  return "fres.";
    case PPCOp::FSEL:   return "fsel";
    case PPCOp::MFFS:   return "mffs";
    case PPCOp::MTFSF:  return "mtfsf";
    case PPCOp::MTFSFI: return "mtfsfi";
    case PPCOp::MTFSB0: return "mtfsb0";
    case PPCOp::MTFSB1: return "mtfsb1";
    case PPCOp::PS_ADD:    return rc ? "ps_add."    : "ps_add";
    case PPCOp::PS_SUB:    return rc ? "ps_sub."    : "ps_sub";
    case PPCOp::PS_MUL:    return rc ? "ps_mul."    : "ps_mul";
    case PPCOp::PS_DIV:    return rc ? "ps_div."    : "ps_div";
    case PPCOp::PS_MADD:   return rc ? "ps_madd."   : "ps_madd";
    case PPCOp::PS_MSUB:   return rc ? "ps_msub."   : "ps_msub";
    case PPCOp::PS_NMADD:  return rc ? "ps_nmadd."  : "ps_nmadd";
    case PPCOp::PS_NMSUB:  return rc ? "ps_nmsub."  : "ps_nmsub";
    case PPCOp::PS_ABS:    return rc ? "ps_abs."    : "ps_abs";
    case PPCOp::PS_NABS:   return rc ? "ps_nabs."   : "ps_nabs";
    case PPCOp::PS_NEG:    return rc ? "ps_neg."    : "ps_neg";
    case PPCOp::PS_MR:     return rc ? "ps_mr."     : "ps_mr";
    case PPCOp::PS_SUM0:   return "ps_sum0";
    case PPCOp::PS_SUM1:   return "ps_sum1";
    case PPCOp::PS_MULS0:  return "ps_muls0";
    case PPCOp::PS_MULS1:  return "ps_muls1";
    case PPCOp::PS_MADDS0: return "ps_madds0";
    case PPCOp::PS_MADDS1: return "ps_madds1";
    case PPCOp::PS_RES:    return "ps_res";
    case PPCOp::PS_RSQRTE: return "ps_rsqrte";
    case PPCOp::PS_SEL:    return "ps_sel";
    case PPCOp::PS_MERGE00:return "ps_merge00";
    case PPCOp::PS_MERGE01:return "ps_merge01";
    case PPCOp::PS_MERGE10:return "ps_merge10";
    case PPCOp::PS_MERGE11:return "ps_merge11";
    case PPCOp::PS_CMPU0:  return "ps_cmpu0";
    case PPCOp::PS_CMPU1:  return "ps_cmpu1";
    case PPCOp::PS_CMPO0:  return "ps_cmpo0";
    case PPCOp::PS_CMPO1:  return "ps_cmpo1";
    case PPCOp::PSQ_L:     return "psq_l";
    case PPCOp::PSQ_LU:    return "psq_lu";
    case PPCOp::PSQ_LX:    return "psq_lx";
    case PPCOp::PSQ_LUX:   return "psq_lux";
    case PPCOp::PSQ_ST:    return "psq_st";
    case PPCOp::PSQ_STU:   return "psq_stu";
    case PPCOp::PSQ_STX:   return "psq_stx";
    case PPCOp::PSQ_STUX:  return "psq_stux";
    case PPCOp::SC:        return "sc";
    case PPCOp::RFI:       return "rfi";
    case PPCOp::ISYNC:     return "isync";
    case PPCOp::SYNC:      return "sync";
    case PPCOp::EIEIO:     return "eieio";
    case PPCOp::DCBT:      return "dcbt";
    case PPCOp::DCBTST:    return "dcbtst";
    case PPCOp::DCBF:      return "dcbf";
    case PPCOp::DCBI:      return "dcbi";
    case PPCOp::DCBZ:      return "dcbz";
    case PPCOp::ICBI:      return "icbi";
    case PPCOp::TW:        return "tw";
    case PPCOp::TWI:       return "twi";
    case PPCOp::MFSR:      return "mfsr";
    case PPCOp::MFSRIN:    return "mfsrin";
    case PPCOp::MTSR:      return "mtsr";
    case PPCOp::MTSRIN:    return "mtsrin";
    case PPCOp::LWARX:     return "lwarx";
    case PPCOp::STWCX:     return "stwcx.";
    case PPCOp::DCBST:     return "dcbst";
    case PPCOp::MCRFS:     return "mcrfs";
    default:               return "unknown";
    }
}
