// interp60_snapshot.cpp — game-native 60fps interpolation, step 1: capture (prev) per actor.
//
// THE DESIGN (debug_journal/2026-08-05_game_native_interpolation_design.md). Interpolate INSIDE the
// game's own terms: snapshot each actor's transform before its movement runs, then render sub-frames
// by writing lerp(prev, cur, alpha) into the live fields and re-running PreEntry + the draw lists.
// The game recomputes matrices, skinning and dependent geometry from the interpolated transform, so
// things with no model matrix interpolate too — which is exactly what J3DModel-matrix lerping cannot
// do and why the trail jittered under it.
//
// WHERE IT HOOKS. JDrama::TViewObj::testPerform (US 0x802fcc94) is the dispatch funnel: non-virtual,
// and every container routes through it (TPerformList::forEachPerform, TViewObjPtrListT::perform,
// TStrategy, TObjManager, TViewConnecter, TScreen, TDirector). Established by measurement on the
// decomp side, where five attempts to reach actors by walking the object graph each stopped at a
// container type nobody had anticipated.
//
// TYPE SAFETY, AND WHY IT IS NOT OPTIONAL. testPerform's `this` is a TViewObj*, and NOT every
// TViewObj is a TActor -- perform lists, screens, view connecters and 2D screens are not. mPosition
// lives at guest +0x10 on TPlacement; writing a transform there on a non-actor corrupts whatever
// that object keeps at 0x10, and would surface later as some unrelated subsystem misbehaving. The
// decomp gets this for free from a virtual; across the guest boundary there is only an address.
//
// So membership is tested against kTActorVtables (generated by tools/re/us_vtables.py, validated
// against 133 live vptrs dumped from a running Delfino frame: precision 47/47, recall 47/49). The
// failure modes are ASYMMETRIC and the list is built to respect that -- a false negative merely
// means an actor does not interpolate, a false positive corrupts memory. Membership is proven,
// never assumed.
//
// THIS FILE ONLY READS GUEST MEMORY. No transform is written yet. (prev) must be shown to differ
// from (cur) for real actors first, because an inert prev/cur pair renders identically to a working
// one -- interpolation built on a dead snapshot would look correct while doing nothing.

#include "overrides.h"
#include "tactor_vtables.h"

#include <intrinsics.h>
#include <lucent/log.h>

#include <cstdlib>
#include <cmath>
#include <cstdio>

extern "C" void func_802fcc94(CPUState&);      // JDrama::TViewObj::testPerform(u32, TGraphics*)
extern "C" unsigned VIGetRetraceCount(void);
// TPerformList::perform(u32 cue, TGraphics*). The interpolation sub-frame IS a re-issue of a
// subset of these calls, so this file owns the seam; the tick-split diagnostic is invoked from it.
extern "C" void sbr_tick_split_call(CPUState&);
// Diagnostic in diag_vptr.cpp. One guest address gets exactly ONE override, so that file no longer
// registers; it is called from here instead (the pattern afterimage.cpp uses).
extern "C" void sbr_vptr_note(unsigned obj);
// Where the GX parser is in this frame's stream (runtime/native_render.h). Used to price the re-issue.
uint32_t sbr_gxfifo_stream_pos();

namespace {

// Guest field offsets. JDrama::TPlacement::mPosition @ 0x10, JDrama::TActor::mRotation @ 0x30
// (decomp include/JSystem/JDrama/JDRPlacement.hpp, JDRActor.hpp). Guest floats are big-endian.
constexpr u32 OFF_POSITION = 0x10;
constexpr u32 OFF_ROTATION = 0x30;

constexpr u32 CUE_MOVE  = 0x1;
constexpr u32 CUE_CALC_ANIM = 0x2;
constexpr u32 CUE_DRAW      = 0x8;   // calcRootMatrix runs HERE, not in the draw phase

// SBR_INTERP60_ALPHA: write lerp(prev, cur, alpha) into the guest transform for the draw phase.
// Unset means snapshot-only (read nothing back). alpha=1.0 MUST be pixel-identical to unset --
// that is the control for the write path itself, before interpolation is attempted. alpha=0.0
// renders the PREVIOUS tick's pose and must visibly differ, or the write is reaching nothing.
float alpha_setting() {
    static const float a = [] {
        const char* e = std::getenv("SBR_INTERP60_ALPHA");
        return e ? (float)std::atof(e) : -1.0f;
    }();
    return a;
}

bool enabled() {
    static const bool on = std::getenv("SBR_INTERP60") != nullptr;
    return on;
}

float guest_f32(u32 ea) {
    const u32 bits = sb_r32(ea);
    float f;
    __builtin_memcpy(&f, &bits, sizeof f);
    return f;
}

bool is_tactor(u32 vptr) {
    // kTActorVtables is emitted sorted; binary search keeps this off the profile.
    int lo = 0, hi = (int)(sizeof(kTActorVtables) / sizeof(kTActorVtables[0])) - 1;
    while (lo <= hi) {
        const int mid = (lo + hi) / 2;
        if (kTActorVtables[mid] == vptr) return true;
        if (kTActorVtables[mid] < vptr) lo = mid + 1; else hi = mid - 1;
    }
    return false;
}

// ── (prev) side table ────────────────────────────────────────────────────────
// Keyed by guest address. A guest object can be freed and its address reused, so every entry
// carries the tick it was written on; an entry older than one tick is treated as absent rather
// than interpolated from, which would otherwise blend a dead object's transform into a live one.
// Open-addressed and fixed-size: no allocation on the game thread.
constexpr int TABLE_BITS = 13;                 // 8192 slots
constexpr int TABLE_SIZE = 1 << TABLE_BITS;
constexpr int TABLE_MASK = TABLE_SIZE - 1;

struct Entry {
    u32   obj  = 0;        // guest address, 0 = empty
    u32   tick = 0;
    float pos[3] = {0, 0, 0};   // (prev): transform before this tick's movement
    float rot[3] = {0, 0, 0};
    float cur[3] = {0, 0, 0};   // (cur): saved at apply time so restore is exact
    float curRot[3] = {0, 0, 0};
    bool  applied = false;      // a lerp is currently written into guest memory
};

Entry g_tab[TABLE_SIZE];
long  g_evictions = 0;     // a full probe chain: capacity exceeded, and it must be visible

Entry* slot_for(u32 obj) {
    u32 h = obj * 2654435761u;
    for (int i = 0; i < 64; ++i) {
        Entry& e = g_tab[(h + (u32)i) & TABLE_MASK];
        if (e.obj == obj || e.obj == 0) return &e;
    }
    ++g_evictions;
    return nullptr;
}

u32  g_seenLists[32];
int  g_seenN = 0;
u32  g_mardir = 0;

void note_seen(u32 list) {
    for (int i = 0; i < g_seenN; ++i) if (g_seenLists[i] == list) return;
    if (g_seenN < 32) g_seenLists[g_seenN++] = list;
}

bool seen(u32 v) {
    for (int i = 0; i < g_seenN; ++i) if (g_seenLists[i] == v) return true;
    return false;
}

constexpr u32 SUBFRAME_CUE_DEFAULT = 0xFFFFFFFCu;
constexpr u32 OFF_PREENTRY = 0x34;

bool  g_inSubframe = false;      // suppress snapshot + instrumentation during the re-issue
u8    g_gfxSnap[0x100];
bool  g_gfxValid = false;
u32   g_drawLists[8];            // the lists the game performed BEFORE its movement phase
u32   g_drawCues[8];
int   g_drawN = 0;
bool  g_sawMovement = false;     // the draw block ends at the first movement-phase list
long  g_subframes = 0, g_subframeSkips = 0;
u32   g_gameTick = 0;            // one per guest tick; presents no longer count 1:1

u32 subframe_cue() {
    static const u32 v = [] {
        const char* e = std::getenv("SBR_INTERP60_MASK");
        return e ? (u32)std::strtoul(e, nullptr, 0) : SUBFRAME_CUE_DEFAULT;
    }();
    return v;
}

// How much (prev) and (cur) actually differ AT APPLY TIME. This is the number that separates
// "interpolation had no visible effect" from "there was nothing to interpolate": if every entry has
// prev == cur when the sub-frame is built, then alpha cannot change the image no matter how
// correct the write path is, and every pixel diff between alphas will read 0 for a reason that has
// nothing to do with the renderer. Carries its denominator, and names the largest mover.
long  g_applyN = 0, g_applyDiff = 0;
float g_applyMax = 0.0f;
u32   g_applyMaxObj = 0;

// ── motion probe ─────────────────────────────────────────────────────────────
// Designed negative-first: "interpolation changed nothing" cannot distinguish a correct
// implementation from a snapshot that captures nothing, so this always reports its DENOMINATOR and
// names the largest mover. If the biggest mover is an ambient prop rather than the player, the
// allowlist is missing the things that matter and the name says so.
long        g_samples = 0, g_moved = 0, g_nonActors = 0, g_actors = 0;
long        g_applied = 0, g_restored = 0;
long        g_writeStuck = 0, g_writeLost = 0;
// The tick value the most recent snapshot was stamped with. apply_all() keys on THIS rather than
// on VIGetRetraceCount(): the draw-phase dispatch does not reliably share the present counter's
// value with the movement dispatch (direct() has an entry-vs-render alternation), so requiring
// exact equality with the present counter matched no entries and the write silently never fired.
u32         g_lastSnapTick = 0xFFFFFFFFu;
float       g_maxStep = 0.0f;
u32         g_maxObj = 0;
float       g_tickMaxStep = 0.0f;   // per-window, so one init teleport cannot mask the steady state
u32         g_tickMaxObj = 0;
unsigned    g_lastReport = 0;

// Read a TNameRef's name (vptr @ 0x00, const char* mName @ 0x04). The largest mover must be
// NAMED: "maxStep=2200" is equally consistent with the player walking and with one prop teleporting
// once at init, and only the name separates them.
void guest_name(u32 obj, char* out, size_t cap) {
    out[0] = '\0';
    if (!sb_ram_fast(obj)) return;
    const u32 p = sb_r32(obj + 4);
    if (!sb_ram_fast(p)) { std::snprintf(out, cap, "<unreadable>"); return; }
    size_t i = 0;
    for (; i + 1 < cap; ++i) {
        const u8 c = sb_r8(p + (u32)i);
        if (c == 0) break;
        out[i] = (char)c;
    }
    out[i] = '\0';
}

void report() {
    char nm[48]; guest_name(g_maxObj, nm, sizeof nm);
    char tick_nm[48]; guest_name(g_tickMaxObj, tick_nm, sizeof tick_nm);
    lucent::info("interp60",
                 "SNAPSHOT: dispatches={} (tactor={} non-actor={}) | compared={} moved={} ({:.1f}%) "
                 "| maxStep all-time={:.2f} \"{}\"  this-window={:.2f} \"{}\"  evictions={}",
                 g_actors + g_nonActors, g_actors, g_nonActors, g_samples, g_moved,
                 g_samples ? 100.0 * (double)g_moved / (double)g_samples : 0.0,
                 (double)g_maxStep, nm, (double)g_tickMaxStep, tick_nm, g_evictions);
    if (alpha_setting() >= 0.0f)
        lucent::info("interp60", "  WRITE alpha={:.2f}: applied={} restored={} (unequal counts mean "
                                 "a pose was left interpolated into the physics step)",
                     (double)alpha_setting(), g_applied, g_restored);
    {
        char am[48]; guest_name(g_applyMaxObj, am, sizeof am);
        lucent::info("interp60",
                     "  AT APPLY TIME: {} entries substituted, {} had prev != cur ({:.1f}%), "
                     "largest delta {:.2f} \"{}\" -- if this is 0 there is nothing to interpolate "
                     "and alpha cannot change the image",
                     g_applyN, g_applyDiff,
                     g_applyN ? 100.0 * (double)g_applyDiff / (double)g_applyN : 0.0,
                     (double)g_applyMax, am);
    }
    lucent::info("interp60",
                 "  SUB-FRAMES: rendered={} refused={} (refused = no director / no recorded draw "
                 "block / no TGraphics snapshot / no snapshot tick -- a refusal renders the tick "
                 "ONCE and is not an error, but a run that is all refusals is 30fps)",
                 g_subframes, g_subframeSkips);
    if (g_subframes && g_drawN == 0 && g_mardir)
        lucent::info("interp60", "  re-issue set: {} lists off gpMarDirector 0x{:08x}", g_drawN,
                     g_mardir);
    if (g_writeStuck || g_writeLost)
        lucent::info("interp60", "  WRITE READ-BACK: stuck={} lost={} (lost>0 means the store never "
                                 "reached the memory the guest reads)", g_writeStuck, g_writeLost);
    g_tickMaxStep = 0.0f; g_tickMaxObj = 0;
    lucent::info("interp60",
                 "  COVERS objects dispatched with CUE_MOVE whose vptr is in kTActorVtables "
                 "(694 entries, validated 47/47 precision on a live frame). Does NOT cover actors "
                 "whose vtable was not recovered, nor non-transform state (JPA particles).");
}

void guest_w_f32(u32 ea, float v) {
    u32 bits;
    __builtin_memcpy(&bits, &v, sizeof bits);
    sb_w32(ea, bits);
}

// Put the guest transforms back exactly as the game left them. Called before movement runs, so
// physics never sees an interpolated pose -- the interpolation is a RENDER-time substitution only,
// which is the whole point of interpolating instead of ticking logic at 60 Hz.
// SBR_INTERP60_NORESTORE=1: leave the substitution in place permanently. Discriminates "the render
// never reads mPosition after the apply" from "restore runs before the render does". Wrong for real
// use -- physics then runs on a substituted pose -- but it is the only way to tell those apart.
bool no_restore() {
    static const bool v = std::getenv("SBR_INTERP60_NORESTORE") != nullptr;
    return v;
}

void restore_all() {
    if (no_restore()) return;
    for (int i = 0; i < TABLE_SIZE; ++i) {
        Entry& e = g_tab[i];
        if (!e.applied) continue;
        e.applied = false;
        if (!sb_ram_fast(e.obj)) continue;
        guest_w_f32(e.obj + OFF_POSITION + 0, e.cur[0]);
        guest_w_f32(e.obj + OFF_POSITION + 4, e.cur[1]);
        guest_w_f32(e.obj + OFF_POSITION + 8, e.cur[2]);
        guest_w_f32(e.obj + OFF_ROTATION + 0, e.curRot[0]);
        guest_w_f32(e.obj + OFF_ROTATION + 4, e.curRot[1]);
        guest_w_f32(e.obj + OFF_ROTATION + 8, e.curRot[2]);
        ++g_restored;
    }
}

// Substitute lerp(prev, cur, alpha) for the draw phase. `cur` is read here rather than tracked
// separately, so restore_all() writes back exactly what the game computed -- no drift from a
// value reconstructed out of the lerp.
void apply_all(u32 tick, float alpha) {
    for (int i = 0; i < TABLE_SIZE; ++i) {
        Entry& e = g_tab[i];
        if (e.obj == 0 || e.tick != tick || e.applied) continue;
        if (!sb_ram_fast(e.obj)) continue;
        for (int k = 0; k < 3; ++k) {
            e.cur[k]    = guest_f32(e.obj + OFF_POSITION + (u32)k * 4);
            e.curRot[k] = guest_f32(e.obj + OFF_ROTATION + (u32)k * 4);
        }
        ++g_applyN;
        {
            const float dx = e.cur[0] - e.pos[0], dy = e.cur[1] - e.pos[1], dz = e.cur[2] - e.pos[2];
            const float d2 = dx * dx + dy * dy + dz * dz;
            if (d2 > 0.0f) {
                ++g_applyDiff;
                const float d = std::sqrt(d2);
                if (d > g_applyMax) { g_applyMax = d; g_applyMaxObj = e.obj; }
            }
        }
        e.applied = true;

        // SBR_INTERP60_KICK=<units>: POSITIVE CONTROL for the write path. alpha=0.0 producing an
        // identical frame is ambiguous — it means either the write reaches nothing, or (prev, cur)
        // are equal for everything actually on screen. A large constant displacement removes that
        // ambiguity: if the frame still does not change, the write provably never reaches rendered
        // state, and no amount of refining the lerp would have shown it.
        static const float kick = [] {
            const char* e2 = std::getenv("SBR_INTERP60_KICK");
            return e2 ? (float)std::atof(e2) : 0.0f;
        }();
        if (kick != 0.0f) {
            const float want = e.cur[1] + kick;
            guest_w_f32(e.obj + OFF_POSITION + 4, want);
            // READ-BACK CHECK. "The write had no visible effect" has two causes that look the same:
            // the store did not stick, or it stuck and nothing read it. Only a read-back separates
            // them, and it must be counted rather than assumed.
            const float got = guest_f32(e.obj + OFF_POSITION + 4);
            if (got == want) ++g_writeStuck; else ++g_writeLost;
            ++g_applied;
            continue;
        }
        // ENDPOINT EXACTNESS is a correctness requirement, not a nicety. alpha=1.0 must reproduce
        // the game's own transform BIT-FOR-BIT, because that is the control proving the write path
        // is a no-op when it should be. `p + (c-p)*a` fails it: the subtraction and the addition
        // each round, so a=1 does not return c and the frame differed by 7,273 pixels. Writing the
        // endpoints directly, and using the (1-a)*p + a*c form in between, is exact at both ends.
        if (alpha >= 1.0f) {
            for (int k = 0; k < 3; ++k) {
                guest_w_f32(e.obj + OFF_POSITION + (u32)k * 4, e.cur[k]);
                guest_w_f32(e.obj + OFF_ROTATION + (u32)k * 4, e.curRot[k]);
            }
            ++g_applied;
            continue;
        }
        if (alpha <= 0.0f) {
            for (int k = 0; k < 3; ++k) {
                guest_w_f32(e.obj + OFF_POSITION + (u32)k * 4, e.pos[k]);
                guest_w_f32(e.obj + OFF_ROTATION + (u32)k * 4, e.rot[k]);
            }
            ++g_applied;
            continue;
        }
        for (int k = 0; k < 3; ++k) {
            guest_w_f32(e.obj + OFF_POSITION + (u32)k * 4,
                        (1.0f - alpha) * e.pos[k] + alpha * e.cur[k]);
            // Angles are Euler degrees here; a naive lerp is wrong across the +-180 seam. Take the
            // shortest arc rather than sweeping the long way round, which would spin an actor a
            // full turn in one sub-frame whenever it crossed the wrap point.
            float d = e.curRot[k] - e.rot[k];
            while (d > 180.0f)  d -= 360.0f;
            while (d < -180.0f) d += 360.0f;
            guest_w_f32(e.obj + OFF_ROTATION + (u32)k * 4, e.rot[k] + d * alpha);
        }
        ++g_applied;
    }
}

// SBR_INTERP60_TRACE=1: the ORDER of phase dispatches relative to the present boundary, for a few
// ticks. Two placements of apply/restore have now been derived by reasoning about that order and
// both were wrong -- the first left the substitution invisible, the second froze every actor by
// writing stale values over movement the game had already done. The order is cheap to observe and
// expensive to guess.
bool trace_on() {
    static const bool v = std::getenv("SBR_INTERP60_TRACE") != nullptr;
    return v;
}
long g_traceLines = 0;
u32  g_lastTraceMask = 0xFFFFFFFFu;
long g_traceRun = 0;          // dispatches collapsed into the current run
long g_tracePresents = 0;

// The trace has to start LATE and it has to be complete, and the first version was neither.
//
// It began at boot, where the scene is a loading screen, and it capped at 90 transitions -- so it
// truncated inside the first tick and the sequence it printed was read as "the tick's phase order".
// That reading put the DRAW lists at the START of a direct() call, which is the opposite of what
// MarDirectorDirect.cpp does (movement -> calcAnim -> PreEntry -> the draw lists). The bracket built
// on it consequently covered a handful of early 0x8 dispatches and none of the actual draw lists.
//
// The draw lists dispatch with mask 0xffffffff, which is why a `mask & 0x8` test both matched them
// and matched almost everything else -- a test that cannot separate the phases cannot place a
// bracket. So: start after the scene is live, count how many dispatches each run collapses (a run
// of 3 and a run of 900 are very different things and the old output showed both as one line), and
// never silently truncate -- say when the cap is hit.
long trace_start_present() {
    static const long v = [] {
        const char* e = std::getenv("SBR_INTERP60_TRACE_AT");
        return e ? std::atol(e) : 800L;
    }();
    return v;
}

void trace_flush_run() {
    if (g_traceRun == 0) return;
    lucent::info("i60trace", "  mask=0x{:<10x} x{}", g_lastTraceMask, g_traceRun);
    g_traceRun = 0;
    ++g_traceLines;
}

void trace_dispatch(u32 mask) {
    if (!trace_on()) return;
    if ((long)VIGetRetraceCount() < trace_start_present()) return;
    if (g_tracePresents > 3) return;
    if (g_traceLines == 400) { ++g_traceLines;
        lucent::info("i60trace", "  [TRUNCATED at 400 runs -- the sequence below is INCOMPLETE]");
        return; }
    if (g_traceLines > 400) return;
    if (mask == g_lastTraceMask) { ++g_traceRun; return; }
    trace_flush_run();
    g_lastTraceMask = mask;
    g_traceRun = 1;
}

// SBR_INTERP60_FOLLOW=<guest addr>: follow ONE actor's mPosition.y through a tick, printing it at
// every phase transition. Three placements of apply/restore have been reasoned about and all three
// were wrong; the frame is the far end of a long chain (pose -> calcRootMatrix -> base TRMtx ->
// entry -> draw) and a pixel diff cannot say WHERE the chain breaks. This reads the value itself.
u32 follow_obj() {
    // "mario" dereferences gpMarioOriginal (0x8040E10C) rather than needing the address of the
    // day; anything else is taken as a literal guest address.
    static const char* e = std::getenv("SBR_INTERP60_FOLLOW");
    if (!e) return 0;
    if (e[0] == 'm') return sb_ram_fast(0x8040E10Cu) ? sb_r32(0x8040E10Cu) : 0u;
    static const u32 a = (u32)std::strtoul(e, nullptr, 0);
    return a;
}
long g_followLines = 0;
u32  g_followLastMask = 0xFFFFFFFFu;

void follow(u32 mask, const char* where) {
    const u32 o = follow_obj();
    if (!o || g_followLines > 60) return;
    if (mask == g_followLastMask && where[0] == 'd') return;
    g_followLastMask = mask;
    ++g_followLines;
    lucent::info("i60follow", "  mask=0x{:<9x} {:<8} y={:.2f}", mask, where,
                 (double)guest_f32(o + OFF_POSITION + 4));
}

// ── the perform-list seam ────────────────────────────────────────────────────
// SBR_INTERP60_LISTS=1: the ORDERED sequence of outermost TPerformList::perform calls in a tick,
// with each list's object address, cue mask, and how many testPerform dispatches ran inside it.
//
// WHY THIS AND NOT A SYMBOL. The sub-frame body is `PreEntry` + the draw lists, which live at
// gpMarDirector +0x34 and +{0x40,0x38,0x3C,0x1C,0x20,0x24} (MarDirector.hpp). gpMarDirector's US
// address is not in reference/sms_gmse01_funcs.txt and the JP symbol (0x8040A2A8) does not carry
// over. But the calls identify themselves: MarDirectorDirect.cpp issues movement and calcAnim with
// computed cues and then PreEntry and every draw list with the literal 0xffffffff, in a fixed
// order, once per tick. Reading that sequence off a running frame gives both the boundary and the
// list POINTERS, without depending on a symbol that may not exist for this region.
//
// The dispatch count matters as much as the address: it separates the heavy scene lists from the
// near-empty ones, so a re-issue set can be justified by what it actually draws rather than by
// which offsets a header happens to name. And it is the denominator for "the re-issue emitted
// nothing" — a count of zero must read as zero, not as absent.
bool lists_on() {
    static const bool v = std::getenv("SBR_INTERP60_LISTS") != nullptr;
    return v;
}
int  g_listDepth = 0;
long g_listDispatches = 0;      // testPerform calls since the current outermost list opened
long g_listTicks = 0;
long g_listLines = 0;
int  g_listSeq = 0;

// ── resolving TMarDirector from the observed list pointers ───────────────────
// The re-issue set is named by FIELD (mPerformListPreEntry @ +0x34, DrawBufGroup @ +0x40,
// Graffito @ +0x38, Pollution @ +0x3C, GX @ +0x1C, Silhouette @ +0x20, GXPost @ +0x24 --
// MarDirector.hpp:177-190), so the ordered call sequence alone is not enough: it says WHICH
// objects are performed, not which of them is PreEntry. Mapping needs gpMarDirector, whose US
// address is absent from reference/sms_gmse01_funcs.txt (the JP symbol 0x8040A2A8 does not carry
// over, and a wrong pointer here would silently mis-label every list).
//
// So find the object instead of the symbol: TMarDirector is the unique structure holding ALL of
// the observed list pointers at exactly those offsets. Scan for it. This is self-validating in a
// way a symbol constant is not -- a candidate either satisfies every offset simultaneously or it
// is not the director -- and it reports its denominator and its candidate COUNT, because "found
// one" and "found eleven, took the first" must not print the same way.
constexpr u32 kListSlots[] = {0x1C, 0x20, 0x24, 0x28, 0x2C, 0x30, 0x34, 0x38, 0x3C, 0x40, 0x44, 0x48};
const char* const kListNames[] = {"GX", "Silhouette", "GXPost", "Movement", "CalcAnim", "unk30",
                                  "PreEntry", "Graffito", "Pollution", "DrawBufGroup",
                                  "ShinePfLstMov", "ShinePfLstAnm"};


// Anchored on the four slots a director must hold and that a stray coincidence will not: two draw
// lists, PreEntry, and movement. Requiring four simultaneous hits from a set of at most a dozen
// addresses makes a false match vanishingly unlikely, and the count below proves it empirically
// rather than by that argument.
void resolve_mardir() {
    if (g_mardir || g_seenN < 6) return;
    long scanned = 0, cands = 0;
    u32 first = 0;
    for (u32 a = 0x80000000u; a < 0x81800000u; a += 4) {
        if (!sb_ram_fast(a) || !sb_ram_fast(a + 0x48)) continue;
        ++scanned;
        if (!seen(sb_r32(a + 0x34))) continue;      // PreEntry
        if (!seen(sb_r32(a + 0x40))) continue;      // DrawBufGroup
        if (!seen(sb_r32(a + 0x1C))) continue;      // GX
        if (!seen(sb_r32(a + 0x28))) continue;      // Movement
        ++cands;
        if (!first) first = a;
    }
    lucent::info("i60lists", "TMarDirector scan: {} words examined, {} candidate(s) matched all "
                             "four anchor slots (PreEntry/DrawBufGroup/GX/Movement)", scanned, cands);
    if (cands == 0) {
        lucent::info("i60lists", "  NO DIRECTOR FOUND. The re-issue set cannot be named by field, "
                                 "and nothing downstream may assume one was resolved.");
        return;
    }
    if (cands > 1)
        lucent::info("i60lists", "  MORE THAN ONE candidate -- the anchors do not identify the "
                                 "director uniquely and the first is NOT safe to use.");
    g_mardir = first;
    lucent::info("i60lists", "  gpMarDirector = 0x{:08x}", g_mardir);
    for (size_t i = 0; i < sizeof(kListSlots) / sizeof(kListSlots[0]); ++i) {
        const u32 p = sb_r32(g_mardir + kListSlots[i]);
        lucent::info("i60lists", "    +0x{:02x} {:<14} = 0x{:08x}{}", kListSlots[i], kListNames[i], p,
                     seen(p) ? "   <- performed this tick" : "");
    }
}

// Record the tick's DRAW BLOCK: the run of outermost list performs before the movement phase.
//
// It is recorded rather than hardcoded because the set is scene-dependent -- Silhouette is only
// performed when the shine/silhouette gate is open (MarDirectorDirect.cpp), and a re-issue of a
// fixed list set would either draw something the tick did not or miss something it did. The block
// is delimited by the director's own Movement list, which is the first thing after the draws.
void record_draw_list(u32 list, u32 mask, u32 gfx) {
    if (!g_mardir) return;
    if (list == sb_r32(g_mardir + 0x28)) { g_sawMovement = true; return; }   // draws are over
    if (g_sawMovement) return;
    if (g_drawN >= (int)(sizeof(g_drawLists) / sizeof(g_drawLists[0]))) return;
    g_drawLists[g_drawN] = list;
    g_drawCues[g_drawN]  = mask;
    ++g_drawN;
    // The TGraphics the game passes is a stack temporary of direct(), long gone by the time the
    // seam runs. Snapshot its bytes so the re-issue can hand the lists an identical one; a
    // reconstructed or zeroed TGraphics would change render state in ways no pixel diff could
    // attribute back to here.
    // Refreshed EVERY tick, not captured once. TSmJ3DScn::perform copies the VIEW MATRIX out of
    // this TGraphics (`MTXCopy(param_2->mViewMtx, j3dSys.getViewMtx())`), so a snapshot taken once
    // at the first tick would render every later sub-frame through the camera of that first tick.
    if (!g_gfxValid && sb_ram_fast(gfx) && sb_ram_fast(gfx + 0xFF)) {
        for (u32 i = 0; i < 0x100; ++i) g_gfxSnap[i] = sb_r8(gfx + i);
        g_gfxValid = true;
    }
}

void list_perform(CPUState& cpu) {
    const u32 list = (u32)cpu.gpr[3];
    const u32 mask = (u32)cpu.gpr[4];
    const u32 gfx  = (u32)cpu.gpr[5];
    // Nested performs belong to their outermost ancestor, and nothing inside a sub-frame re-issue
    // is part of the tick's own structure.
    if (g_listDepth != 0 || g_inSubframe || !enabled()) {
        ++g_listDepth;
        sbr_tick_split_call(cpu);
        --g_listDepth;
        return;
    }
    note_seen(list);
    g_listDispatches = 0;
    ++g_listDepth;
    sbr_tick_split_call(cpu);
    --g_listDepth;
    record_draw_list(list, mask, gfx);

    if (lists_on() && (long)VIGetRetraceCount() >= trace_start_present() && g_listTicks <= 2) {
        ++g_listLines;
        lucent::info("i60lists", "  #{:<2} list=0x{:08x} cue=0x{:<10x} gfx=0x{:08x} dispatches={}",
                     g_listSeq++, list, mask, gfx, g_listDispatches);
    }
}

void snapshot(CPUState& cpu, u32 mask) {
    const u32 obj = (u32)cpu.gpr[3];
    if (!sb_ram_fast(obj)) return;
    if (!(mask & CUE_MOVE)) return;

    const u32 vptr = sb_r32(obj);
    if (!is_tactor(vptr)) { ++g_nonActors; return; }
    ++g_actors;

    Entry* e = slot_for(obj);
    if (!e) return;

    // The GUEST TICK, not the present count. A sub-frame adds a second present, so VIGetRetraceCount
    // stops advancing 1:1 with ticks the moment interpolation is on -- and the (prev) entries are
    // keyed on it, so using it would age every entry out after a single tick and silently disable
    // the snapshot exactly when it starts being needed.
    const u32 tick = g_gameTick;
    const float px = guest_f32(obj + OFF_POSITION + 0);
    const float py = guest_f32(obj + OFF_POSITION + 4);
    const float pz = guest_f32(obj + OFF_POSITION + 8);

    if (e->obj == obj && e->tick + 1 >= tick && e->tick != tick) {
        // A live (prev) from the previous tick: measure the step interpolation would cover.
        const float dx = px - e->pos[0], dy = py - e->pos[1], dz = pz - e->pos[2];
        const float d2 = dx * dx + dy * dy + dz * dz;
        ++g_samples;
        if (d2 > 0.0f) {
            ++g_moved;
            const float d = std::sqrt(d2);
            if (d > g_maxStep) { g_maxStep = d; g_maxObj = obj; }
            if (d > g_tickMaxStep) { g_tickMaxStep = d; g_tickMaxObj = obj; }
        }
    }

    if (e->obj == obj && e->tick == tick) return;   // already snapshotted this tick

    e->obj = obj;
    e->tick = tick;
    g_lastSnapTick = tick;
    e->pos[0] = px; e->pos[1] = py; e->pos[2] = pz;
    e->rot[0] = guest_f32(obj + OFF_ROTATION + 0);
    e->rot[1] = guest_f32(obj + OFF_ROTATION + 4);
    e->rot[2] = guest_f32(obj + OFF_ROTATION + 8);
}

// ── the sub-frame: re-issue PreEntry + the draw lists at an interpolated pose ─
//
// THE TICK, AS MEASURED (SBR_INTERP60_LISTS, gpMarDirector resolved by scan):
//
//   #0 DrawBufGroup  #1 Graffito  #2 Pollution  #3 GX  #4 GXPost      <- the DRAW lists
//   #5..#12 Movement / unk30 (four cue-masked pairs)
//   #13 CalcAnim
//   #14 PreEntry                                                     <- bakes the pose
//   PRESENT
//
// The draw lists run FIRST in a call and PreEntry runs LAST, so the frame the seam is about to
// present was drawn from the PREVIOUS tick's PreEntry -- the entry-vs-render alternation. That is
// what makes the insertion point here temporally correct rather than a compromise: at tick N's
// seam the presented image is the pose entered at N-1, and the sub-frame built here is
// lerp(N-1, N, 0.5), so the display sequence is N-1, mid, N, mid, N+1 -- monotonic.
//
// THREE PASSES, AND WHY THE THIRD IS NOT AN UNDO. PreEntry populates the draw buffers that the
// NEXT call consumes, so a sub-frame that leaves an interpolated PreEntry standing would make the
// next tick draw the midpoint instead of tick N. The pass order is therefore:
//
//   1. substitute lerp(prev, cur, alpha), re-issue PreEntry + the draw lists  -> present
//   2. write the true transforms back
//   3. re-issue PreEntry ALONE, so the entered state is tick N's by construction
//
// Pass 3 writes the truth; it is not a correction applied to a wrong value, which is what the
// earlier mutate-and-undo bracket was and why it kept failing.
//
// WHAT IS RE-ISSUED, AND WITH WHAT CUE. Only lists the game itself performed this tick, in the
// order it performed them -- never a hardcoded set, so a scene that skips Silhouette re-issues
// without it too. The cue clears bits 0x1 (movement) and 0x2 (calc-anim): a sub-frame must DRAW,
// not advance state, and re-running those double-steps the water scroll counter and other
// per-frame animation, which the recomp-era implementation RE'd as the cause of a 30 Hz water
// flicker (SBR_INTERP60_MASK overrides it for A/B).

void interp_test_perform(CPUState& cpu) {
    ++g_listDispatches;
    // Inside a sub-frame, report progress by DISPATCH and by stream position. A list that never
    // returns is otherwise a single silent stack sample: these two numbers say whether it is
    // advancing through its objects, stuck on one, or emitting without bound — three different
    // faults that look identical from outside.
    if (g_inSubframe && g_subframes < 2 && (g_listDispatches % 64) == 0)
        lucent::info("i60sub", "     ... dispatch {} of this list, stream={} KB",
                     g_listDispatches, sbr_gxfifo_stream_pos() >> 10);
    if (std::getenv("SBR_VPTR_DUMP")) sbr_vptr_note((unsigned)cpu.gpr[3]);

    if (enabled() && !g_inSubframe) {
        const u32 mask = (u32)cpu.gpr[4];

        trace_dispatch(mask);
        follow(mask, "dispatch");

        // testPerform masks the incoming cue with the object's own unkC before dispatching; the
        // snapshot only needs to know movement is about to run for this object, and the raw cue
        // carries that. Reading it before the body keeps this a pure observation.
        snapshot(cpu, mask);

        const unsigned frame = VIGetRetraceCount();
        if (frame >= g_lastReport + 600) { g_lastReport = frame; report(); }
    }

    func_802fcc94(cpu);
}

// Run one perform list through the real body with a synthesized CPU state. The list bodies are
// ordinary guest code, so they need a plausible stack: the TGraphics is rebuilt from the tick's
// snapshot below the seam's own stack pointer, and every register the call clobbers is restored by
// the caller.
void perform_list(CPUState& cpu, u32 list, u32 cue, u32 gfx) {
    if (!list || !sb_ram_fast(list)) return;
    // The first sub-frames are traced list by list, entry AND exit. A re-issue that hangs inside
    // guest code otherwise produces silence, and silence is the one output that cannot be told from
    // "never ran" -- the exit line is what distinguishes them.
    const bool loud = g_subframes < 2;
    if (loud) lucent::info("i60sub", "  -> list 0x{:08x} cue=0x{:x} stream={} KB", list, cue,
                           sbr_gxfifo_stream_pos() >> 10);
    cpu.gpr[3] = list;
    cpu.gpr[4] = cue;
    cpu.gpr[5] = gfx;
    sbr_tick_split_call(cpu);
    // The GX BYTES this list emitted. "The re-issue hangs" and "the re-issue emits a hundred times
    // the geometry it should" produce the same silence from outside; only the stream size separates
    // them, and a whole tick is about 2.25 MB, so anything far past that is the answer.
    if (loud) lucent::info("i60sub", "  <- list 0x{:08x} returned, stream={} KB", list,
                           sbr_gxfifo_stream_pos() >> 10);
}

} // namespace

// The sub-frame. Called from native_frame.cpp immediately after the tick's own present, with a
// callback that closes the GX stream and presents it.
//
// It REFUSES rather than degrades: no director, no recorded draw block, no TGraphics snapshot, or
// no snapshot tick means no sub-frame, counted and reported. A sub-frame that quietly renders
// nothing would show up as "60fps that looks like 30" with no way to tell it from a bad alpha.
extern "C" void sbr_interp60_subframe(CPUState& cpu, void (*present)(void)) {
    if (!enabled()) return;
    // RE-ENTRANCY. The re-issued lists are ordinary guest code and may reach the frame seam again
    // (anything in them that waits on a retrace does). Without this guard each nesting level starts
    // another sub-frame and the frame never completes -- which presents as a hang, not as an error.
    if (g_inSubframe) return;
    ++g_gameTick;
    g_sawMovement = false;          // next tick records its own draw block
    if (!g_mardir) resolve_mardir();

    const float alpha = alpha_setting();
    if (alpha < 0.0f) { g_drawN = 0; return; }
    if (!g_mardir || g_drawN == 0 || !g_gfxValid || g_lastSnapTick == 0xFFFFFFFFu) {
        ++g_subframeSkips;
        g_drawN = 0;
        return;
    }

    const u32 preEntry = sb_r32(g_mardir + OFF_PREENTRY);

    // Carve the TGraphics and a call frame below the seam's stack. The guest stack grows down and
    // the seam is far from the deepest frame the game uses, so this region is dead space; the old
    // recomp-era implementation used the same construction.
    const u32 savedSp = (u32)cpu.gpr[1];
    const u32 gfx = (savedSp - 0x110u) & ~0xFu;
    for (u32 i = 0; i < 0x100; ++i) sb_w8(gfx + i, g_gfxSnap[i]);
    cpu.gpr[1] = (gfx - 0x20u) & ~0xFu;

    g_inSubframe = true;
    const u32 cue = subframe_cue();

    // NO SEPARATE PreEntry -- and that is a POSITIVE design point, not an omission.
    //
    // TSmJ3DScn::perform (decomp JDRSmJ3DScn.cpp:46) does the whole cycle inside its DRAW cue:
    //
    //     if (param_1 & 8) {
    //         for (i < mDrawBufferCount) mDrawBuffers[i]->frameInit();   // reset
    //         j3dSys.setDrawBuffer(mDrawBuffers[0], 0); ...
    //         TViewObjPtrListT::perform(param_1 | 0x204, param_2);        // enter
    //         mDrawBuffers[0]->draw(); mDrawBuffers[1]->draw();          // draw
    //     }
    //
    // So re-issuing the draw lists resets the scene's buffers and re-enters every object from the
    // pose that is live AT THAT MOMENT -- which is exactly the substitution this file wrote. The
    // scene is self-healing too: the next tick's render branch runs the same reset-enter-draw from
    // the restored pose, so nothing has to be undone.
    //
    // Re-running PreEntry on top of that appended a SECOND entry set into buffers the seam finds
    // already full (PreEntry is the last list of a tick, and its entries are drawn by the NEXT
    // call's render branch -- the entry-vs-render alternation MarDirectorDirect.cpp documents at
    // its ENTRY-side/RENDER-side branches). The following draw then never finished.
    //
    // Measured both ways with the reach probe (tools/interp/interp60_gate.sh --kick 3000):
    // without PreEntry the sub-frame moves 1,193,906 of 1,228,800 pixels (97.16%); the earlier
    // draw-phase bracket moved 0. SBR_INTERP60_PREENTRY=1 restores the old behaviour for A/B and
    // is expected to wedge -- it is kept because a fault this specific should stay reproducible.
    static const bool preEntry_ = std::getenv("SBR_INTERP60_PREENTRY") != nullptr;
    const bool noEntry = !preEntry_;

    // Pass 1: interpolated pose -> enter -> draw -> present.
    apply_all(g_lastSnapTick, alpha);
    if (!noEntry) perform_list(cpu, preEntry, cue, gfx);
    for (int i = 0; i < g_drawN; ++i) perform_list(cpu, g_drawLists[i], g_drawCues[i] & cue, gfx);
    present();

    // Pass 2: the true pose, entered again so the NEXT tick's draw lists consume tick N and not the
    // midpoint. This is the pass that makes the substitution self-cancelling by construction.
    restore_all();
    if (!noEntry) perform_list(cpu, preEntry, cue, gfx);

    g_inSubframe = false;
    cpu.gpr[1] = savedSp;
    ++g_subframes;
    // Reset for the NEXT tick's draw block -- AFTER this sub-frame has consumed them, never before.
    // The draw block is recorded EARLY in a call and the seam runs at the end of it, so clearing
    // these on entry throws away the very recording being used (measured: rendered=0, refused=1200,
    // every tick refusing for want of the TGraphics it had just captured).
    g_drawN = 0;
    g_gfxValid = false;
}

// Called from native_frame.cpp's present path, after aurora has consumed the frame's GX stream.
extern "C" void sbr_interp60_restore() {
    if (!enabled()) return;
    if (trace_on() && (long)VIGetRetraceCount() >= trace_start_present() && g_tracePresents <= 3) {
        trace_flush_run();
        ++g_tracePresents;
        lucent::info("i60trace", "PRESENT  (end of tick {})", g_tracePresents);
    }
    if (lists_on() && (long)VIGetRetraceCount() >= trace_start_present() && g_listTicks <= 2) {
        ++g_listTicks;
        lucent::info("i60lists", "PRESENT  (end of tick {}; {} outermost perform calls so far)",
                     g_listTicks, g_listLines);
        if (g_listLines == 0)
            lucent::info("i60lists", "  NOTE: zero outermost calls were seen this tick -- the "
                                     "sub-frame body cannot be built from a sequence that is empty");
        g_listSeq = 0;
        if (g_listTicks == 2) resolve_mardir();   // after a full tick has populated the seen-set
    }
}

SB_OVERRIDE(0x802a4e28, list_perform, "TPerformList::perform",
            "60fps interpolation (SBR_INTERP60_LISTS): identify the tick's ordered perform-list "
            "calls, which are what a sub-frame re-issues; always runs the real body")

SB_OVERRIDE(0x802fcc94, interp_test_perform, "JDrama::TViewObj::testPerform",
            "60fps interpolation (SBR_INTERP60): snapshot each actor's transform before its "
            "movement; reads guest memory only, writes nothing; always runs the real body")
