// interp60_snapshot.cpp — game-native 60fps interpolation, step 1: capture (prev) per actor.
//
// THE DESIGN (debug_journal/2026-08-05_game_native_interpolation_design.md). Interpolate INSIDE the
// game's own terms: snapshot each actor's transform before its movement runs, then render sub-frames
// by writing lerp(prev, cur, alpha) into the live fields and re-running PreEntry + the draw lists.
// The game recomputes matrices, skinning and dependent geometry from the interpolated transform, so
// things with no model matrix interpolate too — which is exactly what J3DModel-matrix lerping cannot
// do and why the trail jittered under it.
//
// WHERE IT HOOKS. JDrama::TViewObj::testPerform (US 0x802fcc94) is the dispatch funnel: non-virtual,
// and every container routes through it (TPerformList::forEachPerform, TViewObjPtrListT::perform,
// TStrategy, TObjManager, TViewConnecter, TScreen, TDirector). Established by measurement on the
// decomp side, where five attempts to reach actors by walking the object graph each stopped at a
// container type nobody had anticipated.
//
// TYPE SAFETY, AND WHY IT IS NOT OPTIONAL. testPerform's `this` is a TViewObj*, and NOT every
// TViewObj is a TActor -- perform lists, screens, view connecters and 2D screens are not. mPosition
// lives at guest +0x10 on TPlacement; writing a transform there on a non-actor corrupts whatever
// that object keeps at 0x10, and would surface later as some unrelated subsystem misbehaving. The
// decomp gets this for free from a virtual; across the guest boundary there is only an address.
//
// So membership is tested against kTActorVtables (generated by tools/re/us_vtables.py, validated
// against 133 live vptrs dumped from a running Delfino frame: precision 47/47, recall 47/49). The
// failure modes are ASYMMETRIC and the list is built to respect that -- a false negative merely
// means an actor does not interpolate, a false positive corrupts memory. Membership is proven,
// never assumed.
//
// THIS FILE ONLY READS GUEST MEMORY. No transform is written yet. (prev) must be shown to differ
// from (cur) for real actors first, because an inert prev/cur pair renders identically to a working
// one -- interpolation built on a dead snapshot would look correct while doing nothing.

#include "overrides.h"
#include "tactor_vtables.h"

#include <intrinsics.h>
#include <lucent/log.h>

#include <cstdlib>
#include <cmath>
#include <cstdio>

extern "C" void func_802fcc94(CPUState&);      // JDrama::TViewObj::testPerform(u32, TGraphics*)
extern "C" unsigned VIGetRetraceCount(void);
// Diagnostic in diag_vptr.cpp. One guest address gets exactly ONE override, so that file no longer
// registers; it is called from here instead (the pattern afterimage.cpp uses).
extern "C" void sbr_vptr_note(unsigned obj);

namespace {

// Guest field offsets. JDrama::TPlacement::mPosition @ 0x10, JDrama::TActor::mRotation @ 0x30
// (decomp include/JSystem/JDrama/JDRPlacement.hpp, JDRActor.hpp). Guest floats are big-endian.
constexpr u32 OFF_POSITION = 0x10;
constexpr u32 OFF_ROTATION = 0x30;

constexpr u32 CUE_MOVE  = 0x1;
constexpr u32 CUE_CALC_ANIM = 0x2;
constexpr u32 CUE_DRAW      = 0x8;   // calcRootMatrix runs HERE, not in the draw phase

// SBR_INTERP60_ALPHA: write lerp(prev, cur, alpha) into the guest transform for the draw phase.
// Unset means snapshot-only (read nothing back). alpha=1.0 MUST be pixel-identical to unset --
// that is the control for the write path itself, before interpolation is attempted. alpha=0.0
// renders the PREVIOUS tick's pose and must visibly differ, or the write is reaching nothing.
float alpha_setting() {
    static const float a = [] {
        const char* e = std::getenv("SBR_INTERP60_ALPHA");
        return e ? (float)std::atof(e) : -1.0f;
    }();
    return a;
}

bool enabled() {
    static const bool on = std::getenv("SBR_INTERP60") != nullptr;
    return on;
}

float guest_f32(u32 ea) {
    const u32 bits = sb_r32(ea);
    float f;
    __builtin_memcpy(&f, &bits, sizeof f);
    return f;
}

bool is_tactor(u32 vptr) {
    // kTActorVtables is emitted sorted; binary search keeps this off the profile.
    int lo = 0, hi = (int)(sizeof(kTActorVtables) / sizeof(kTActorVtables[0])) - 1;
    while (lo <= hi) {
        const int mid = (lo + hi) / 2;
        if (kTActorVtables[mid] == vptr) return true;
        if (kTActorVtables[mid] < vptr) lo = mid + 1; else hi = mid - 1;
    }
    return false;
}

// ── (prev) side table ────────────────────────────────────────────────────────
// Keyed by guest address. A guest object can be freed and its address reused, so every entry
// carries the tick it was written on; an entry older than one tick is treated as absent rather
// than interpolated from, which would otherwise blend a dead object's transform into a live one.
// Open-addressed and fixed-size: no allocation on the game thread.
constexpr int TABLE_BITS = 13;                 // 8192 slots
constexpr int TABLE_SIZE = 1 << TABLE_BITS;
constexpr int TABLE_MASK = TABLE_SIZE - 1;

struct Entry {
    u32   obj  = 0;        // guest address, 0 = empty
    u32   tick = 0;
    float pos[3] = {0, 0, 0};   // (prev): transform before this tick's movement
    float rot[3] = {0, 0, 0};
    float cur[3] = {0, 0, 0};   // (cur): saved at apply time so restore is exact
    float curRot[3] = {0, 0, 0};
    bool  applied = false;      // a lerp is currently written into guest memory
};

Entry g_tab[TABLE_SIZE];
long  g_evictions = 0;     // a full probe chain: capacity exceeded, and it must be visible

Entry* slot_for(u32 obj) {
    u32 h = obj * 2654435761u;
    for (int i = 0; i < 64; ++i) {
        Entry& e = g_tab[(h + (u32)i) & TABLE_MASK];
        if (e.obj == obj || e.obj == 0) return &e;
    }
    ++g_evictions;
    return nullptr;
}

// ── motion probe ─────────────────────────────────────────────────────────────
// Designed negative-first: "interpolation changed nothing" cannot distinguish a correct
// implementation from a snapshot that captures nothing, so this always reports its DENOMINATOR and
// names the largest mover. If the biggest mover is an ambient prop rather than the player, the
// allowlist is missing the things that matter and the name says so.
long        g_samples = 0, g_moved = 0, g_nonActors = 0, g_actors = 0;
long        g_applied = 0, g_restored = 0;
long        g_writeStuck = 0, g_writeLost = 0;
// The tick value the most recent snapshot was stamped with. apply_all() keys on THIS rather than
// on VIGetRetraceCount(): the draw-phase dispatch does not reliably share the present counter's
// value with the movement dispatch (direct() has an entry-vs-render alternation), so requiring
// exact equality with the present counter matched no entries and the write silently never fired.
u32         g_lastSnapTick = 0xFFFFFFFFu;
float       g_maxStep = 0.0f;
u32         g_maxObj = 0;
float       g_tickMaxStep = 0.0f;   // per-window, so one init teleport cannot mask the steady state
u32         g_tickMaxObj = 0;
unsigned    g_lastReport = 0;

// Read a TNameRef's name (vptr @ 0x00, const char* mName @ 0x04). The largest mover must be
// NAMED: "maxStep=2200" is equally consistent with the player walking and with one prop teleporting
// once at init, and only the name separates them.
void guest_name(u32 obj, char* out, size_t cap) {
    out[0] = '\0';
    if (!sb_ram_fast(obj)) return;
    const u32 p = sb_r32(obj + 4);
    if (!sb_ram_fast(p)) { std::snprintf(out, cap, "<unreadable>"); return; }
    size_t i = 0;
    for (; i + 1 < cap; ++i) {
        const u8 c = sb_r8(p + (u32)i);
        if (c == 0) break;
        out[i] = (char)c;
    }
    out[i] = '\0';
}

void report() {
    char nm[48]; guest_name(g_maxObj, nm, sizeof nm);
    char tick_nm[48]; guest_name(g_tickMaxObj, tick_nm, sizeof tick_nm);
    lucent::info("interp60",
                 "SNAPSHOT: dispatches={} (tactor={} non-actor={}) | compared={} moved={} ({:.1f}%) "
                 "| maxStep all-time={:.2f} \"{}\"  this-window={:.2f} \"{}\"  evictions={}",
                 g_actors + g_nonActors, g_actors, g_nonActors, g_samples, g_moved,
                 g_samples ? 100.0 * (double)g_moved / (double)g_samples : 0.0,
                 (double)g_maxStep, nm, (double)g_tickMaxStep, tick_nm, g_evictions);
    if (alpha_setting() >= 0.0f)
        lucent::info("interp60", "  WRITE alpha={:.2f}: applied={} restored={} (unequal counts mean "
                                 "a pose was left interpolated into the physics step)",
                     (double)alpha_setting(), g_applied, g_restored);
    if (g_writeStuck || g_writeLost)
        lucent::info("interp60", "  WRITE READ-BACK: stuck={} lost={} (lost>0 means the store never "
                                 "reached the memory the guest reads)", g_writeStuck, g_writeLost);
    g_tickMaxStep = 0.0f; g_tickMaxObj = 0;
    lucent::info("interp60",
                 "  COVERS objects dispatched with CUE_MOVE whose vptr is in kTActorVtables "
                 "(694 entries, validated 47/47 precision on a live frame). Does NOT cover actors "
                 "whose vtable was not recovered, nor non-transform state (JPA particles).");
}

void guest_w_f32(u32 ea, float v) {
    u32 bits;
    __builtin_memcpy(&bits, &v, sizeof bits);
    sb_w32(ea, bits);
}

// Put the guest transforms back exactly as the game left them. Called before movement runs, so
// physics never sees an interpolated pose -- the interpolation is a RENDER-time substitution only,
// which is the whole point of interpolating instead of ticking logic at 60 Hz.
// SBR_INTERP60_NORESTORE=1: leave the substitution in place permanently. Discriminates "the render
// never reads mPosition after the apply" from "restore runs before the render does". Wrong for real
// use -- physics then runs on a substituted pose -- but it is the only way to tell those apart.
bool no_restore() {
    static const bool v = std::getenv("SBR_INTERP60_NORESTORE") != nullptr;
    return v;
}

void restore_all() {
    if (no_restore()) return;
    for (int i = 0; i < TABLE_SIZE; ++i) {
        Entry& e = g_tab[i];
        if (!e.applied) continue;
        e.applied = false;
        if (!sb_ram_fast(e.obj)) continue;
        guest_w_f32(e.obj + OFF_POSITION + 0, e.cur[0]);
        guest_w_f32(e.obj + OFF_POSITION + 4, e.cur[1]);
        guest_w_f32(e.obj + OFF_POSITION + 8, e.cur[2]);
        guest_w_f32(e.obj + OFF_ROTATION + 0, e.curRot[0]);
        guest_w_f32(e.obj + OFF_ROTATION + 4, e.curRot[1]);
        guest_w_f32(e.obj + OFF_ROTATION + 8, e.curRot[2]);
        ++g_restored;
    }
}

// Substitute lerp(prev, cur, alpha) for the draw phase. `cur` is read here rather than tracked
// separately, so restore_all() writes back exactly what the game computed -- no drift from a
// value reconstructed out of the lerp.
void apply_all(u32 tick, float alpha) {
    for (int i = 0; i < TABLE_SIZE; ++i) {
        Entry& e = g_tab[i];
        if (e.obj == 0 || e.tick != tick || e.applied) continue;
        if (!sb_ram_fast(e.obj)) continue;
        for (int k = 0; k < 3; ++k) {
            e.cur[k]    = guest_f32(e.obj + OFF_POSITION + (u32)k * 4);
            e.curRot[k] = guest_f32(e.obj + OFF_ROTATION + (u32)k * 4);
        }
        e.applied = true;

        // SBR_INTERP60_KICK=<units>: POSITIVE CONTROL for the write path. alpha=0.0 producing an
        // identical frame is ambiguous — it means either the write reaches nothing, or (prev, cur)
        // are equal for everything actually on screen. A large constant displacement removes that
        // ambiguity: if the frame still does not change, the write provably never reaches rendered
        // state, and no amount of refining the lerp would have shown it.
        static const float kick = [] {
            const char* e2 = std::getenv("SBR_INTERP60_KICK");
            return e2 ? (float)std::atof(e2) : 0.0f;
        }();
        if (kick != 0.0f) {
            const float want = e.cur[1] + kick;
            guest_w_f32(e.obj + OFF_POSITION + 4, want);
            // READ-BACK CHECK. "The write had no visible effect" has two causes that look the same:
            // the store did not stick, or it stuck and nothing read it. Only a read-back separates
            // them, and it must be counted rather than assumed.
            const float got = guest_f32(e.obj + OFF_POSITION + 4);
            if (got == want) ++g_writeStuck; else ++g_writeLost;
            ++g_applied;
            continue;
        }
        // ENDPOINT EXACTNESS is a correctness requirement, not a nicety. alpha=1.0 must reproduce
        // the game's own transform BIT-FOR-BIT, because that is the control proving the write path
        // is a no-op when it should be. `p + (c-p)*a` fails it: the subtraction and the addition
        // each round, so a=1 does not return c and the frame differed by 7,273 pixels. Writing the
        // endpoints directly, and using the (1-a)*p + a*c form in between, is exact at both ends.
        if (alpha >= 1.0f) {
            for (int k = 0; k < 3; ++k) {
                guest_w_f32(e.obj + OFF_POSITION + (u32)k * 4, e.cur[k]);
                guest_w_f32(e.obj + OFF_ROTATION + (u32)k * 4, e.curRot[k]);
            }
            ++g_applied;
            continue;
        }
        if (alpha <= 0.0f) {
            for (int k = 0; k < 3; ++k) {
                guest_w_f32(e.obj + OFF_POSITION + (u32)k * 4, e.pos[k]);
                guest_w_f32(e.obj + OFF_ROTATION + (u32)k * 4, e.rot[k]);
            }
            ++g_applied;
            continue;
        }
        for (int k = 0; k < 3; ++k) {
            guest_w_f32(e.obj + OFF_POSITION + (u32)k * 4,
                        (1.0f - alpha) * e.pos[k] + alpha * e.cur[k]);
            // Angles are Euler degrees here; a naive lerp is wrong across the +-180 seam. Take the
            // shortest arc rather than sweeping the long way round, which would spin an actor a
            // full turn in one sub-frame whenever it crossed the wrap point.
            float d = e.curRot[k] - e.rot[k];
            while (d > 180.0f)  d -= 360.0f;
            while (d < -180.0f) d += 360.0f;
            guest_w_f32(e.obj + OFF_ROTATION + (u32)k * 4, e.rot[k] + d * alpha);
        }
        ++g_applied;
    }
}

// SBR_INTERP60_TRACE=1: the ORDER of phase dispatches relative to the present boundary, for a few
// ticks. Two placements of apply/restore have now been derived by reasoning about that order and
// both were wrong -- the first left the substitution invisible, the second froze every actor by
// writing stale values over movement the game had already done. The order is cheap to observe and
// expensive to guess.
bool trace_on() {
    static const bool v = std::getenv("SBR_INTERP60_TRACE") != nullptr;
    return v;
}
long g_traceLines = 0;
u32  g_lastTraceMask = 0xFFFFFFFFu;
long g_traceRun = 0;          // dispatches collapsed into the current run
long g_tracePresents = 0;

// The trace has to start LATE and it has to be complete, and the first version was neither.
//
// It began at boot, where the scene is a loading screen, and it capped at 90 transitions -- so it
// truncated inside the first tick and the sequence it printed was read as "the tick's phase order".
// That reading put the DRAW lists at the START of a direct() call, which is the opposite of what
// MarDirectorDirect.cpp does (movement -> calcAnim -> PreEntry -> the draw lists). The bracket built
// on it consequently covered a handful of early 0x8 dispatches and none of the actual draw lists.
//
// The draw lists dispatch with mask 0xffffffff, which is why a `mask & 0x8` test both matched them
// and matched almost everything else -- a test that cannot separate the phases cannot place a
// bracket. So: start after the scene is live, count how many dispatches each run collapses (a run
// of 3 and a run of 900 are very different things and the old output showed both as one line), and
// never silently truncate -- say when the cap is hit.
long trace_start_present() {
    static const long v = [] {
        const char* e = std::getenv("SBR_INTERP60_TRACE_AT");
        return e ? std::atol(e) : 800L;
    }();
    return v;
}

void trace_flush_run() {
    if (g_traceRun == 0) return;
    lucent::info("i60trace", "  mask=0x{:<10x} x{}", g_lastTraceMask, g_traceRun);
    g_traceRun = 0;
    ++g_traceLines;
}

void trace_dispatch(u32 mask) {
    if (!trace_on()) return;
    if ((long)VIGetRetraceCount() < trace_start_present()) return;
    if (g_tracePresents > 3) return;
    if (g_traceLines == 400) { ++g_traceLines;
        lucent::info("i60trace", "  [TRUNCATED at 400 runs -- the sequence below is INCOMPLETE]");
        return; }
    if (g_traceLines > 400) return;
    if (mask == g_lastTraceMask) { ++g_traceRun; return; }
    trace_flush_run();
    g_lastTraceMask = mask;
    g_traceRun = 1;
}

// SBR_INTERP60_FOLLOW=<guest addr>: follow ONE actor's mPosition.y through a tick, printing it at
// every phase transition. Three placements of apply/restore have been reasoned about and all three
// were wrong; the frame is the far end of a long chain (pose -> calcRootMatrix -> base TRMtx ->
// entry -> draw) and a pixel diff cannot say WHERE the chain breaks. This reads the value itself.
u32 follow_obj() {
    // "mario" dereferences gpMarioOriginal (0x8040E10C) rather than needing the address of the
    // day; anything else is taken as a literal guest address.
    static const char* e = std::getenv("SBR_INTERP60_FOLLOW");
    if (!e) return 0;
    if (e[0] == 'm') return sb_ram_fast(0x8040E10Cu) ? sb_r32(0x8040E10Cu) : 0u;
    static const u32 a = (u32)std::strtoul(e, nullptr, 0);
    return a;
}
long g_followLines = 0;
u32  g_followLastMask = 0xFFFFFFFFu;

void follow(u32 mask, const char* where) {
    const u32 o = follow_obj();
    if (!o || g_followLines > 60) return;
    if (mask == g_followLastMask && where[0] == 'd') return;
    g_followLastMask = mask;
    ++g_followLines;
    lucent::info("i60follow", "  mask=0x{:<9x} {:<8} y={:.2f}", mask, where,
                 (double)guest_f32(o + OFF_POSITION + 4));
}

void snapshot(CPUState& cpu, u32 mask) {
    const u32 obj = (u32)cpu.gpr[3];
    if (!sb_ram_fast(obj)) return;
    if (!(mask & CUE_MOVE)) return;

    const u32 vptr = sb_r32(obj);
    if (!is_tactor(vptr)) { ++g_nonActors; return; }
    ++g_actors;

    Entry* e = slot_for(obj);
    if (!e) return;

    const u32 tick = VIGetRetraceCount();
    const float px = guest_f32(obj + OFF_POSITION + 0);
    const float py = guest_f32(obj + OFF_POSITION + 4);
    const float pz = guest_f32(obj + OFF_POSITION + 8);

    if (e->obj == obj && e->tick + 1 >= tick && e->tick != tick) {
        // A live (prev) from the previous tick: measure the step interpolation would cover.
        const float dx = px - e->pos[0], dy = py - e->pos[1], dz = pz - e->pos[2];
        const float d2 = dx * dx + dy * dy + dz * dz;
        ++g_samples;
        if (d2 > 0.0f) {
            ++g_moved;
            const float d = std::sqrt(d2);
            if (d > g_maxStep) { g_maxStep = d; g_maxObj = obj; }
            if (d > g_tickMaxStep) { g_tickMaxStep = d; g_tickMaxObj = obj; }
        }
    }

    if (e->obj == obj && e->tick == tick) return;   // already snapshotted this tick

    e->obj = obj;
    e->tick = tick;
    g_lastSnapTick = tick;
    e->pos[0] = px; e->pos[1] = py; e->pos[2] = pz;
    e->rot[0] = guest_f32(obj + OFF_ROTATION + 0);
    e->rot[1] = guest_f32(obj + OFF_ROTATION + 4);
    e->rot[2] = guest_f32(obj + OFF_ROTATION + 8);
}

void interp_test_perform(CPUState& cpu) {
    if (std::getenv("SBR_VPTR_DUMP")) sbr_vptr_note((unsigned)cpu.gpr[3]);

    if (enabled()) {
        const u32 mask = (u32)cpu.gpr[4];
        const u32 tick = VIGetRetraceCount();
        const float alpha = alpha_setting();

        if (alpha >= 0.0f) {
            // BRACKET THE DRAW BLOCK, nothing wider.
            //
            // The previous scheme substituted at the calc phase and undid it a phase (or a frame)
            // later. That is mutate-and-undo across phase boundaries, and it needs exact knowledge
            // of every consumer of the pose in between -- three placements were tried and all three
            // were wrong, one of them freezing every actor by overwriting movement the game had
            // already done.
            //
            // The measured dispatch order (SBR_INTERP60_TRACE) shows the draw dispatches form a
            // CONTIGUOUS BLOCK at the start of a direct() call, before movement:
            //     draw (0x8) ... -> movement (0x1) -> calc (0x2) -> view (0x4) -> entry -> PRESENT
            // So the substitution can open at the first draw dispatch and close at the first
            // non-draw dispatch after it. It never outlives the block that uses it, and no phase
            // that reads the pose for anything but drawing ever sees a substituted value.
            //
            // This is still a stand-in for the real design, which renders the tick TWICE (alpha=0.5
            // then alpha=1.0) and needs no undo at all, because the last pass writes the truth.
            //
            // SBR_INTERP60_BRACKET=<mask> moves which phase bit opens the bracket. The draw block
            // is the default and is where a pose SHOULD be consumed, but "the control fires" only
            // proves the write reaches something rendered -- it does not prove the bracket covers
            // the phase that actually bakes poses into geometry. That is an empirical question
            // (--kick in tools/interp/interp60_gate.sh answers it), so the bracket is a knob rather
            // than a constant until the measurement says which phase it belongs on.
            static const u32 bracketBit = [] {
                const char* e2 = std::getenv("SBR_INTERP60_BRACKET");
                return e2 ? (u32)std::strtoul(e2, nullptr, 0) : CUE_DRAW;
            }();
            static bool s_inDraw = false;
            const bool isDraw = (mask & bracketBit) != 0;
            if (isDraw && !s_inDraw) {
                s_inDraw = true;
                apply_all(g_lastSnapTick, alpha);
            } else if (!isDraw && s_inDraw) {
                s_inDraw = false;
                restore_all();
            }
        }

        trace_dispatch(mask);
        follow(mask, "dispatch");

        // testPerform masks the incoming cue with the object's own unkC before dispatching; the
        // snapshot only needs to know movement is about to run for this object, and the raw cue
        // carries that. Reading it before the body keeps this a pure observation.
        snapshot(cpu, mask);

        const unsigned frame = VIGetRetraceCount();
        if (frame >= g_lastReport + 600) { g_lastReport = frame; report(); }
    }

    func_802fcc94(cpu);
}

} // namespace

// Called from native_frame.cpp's present path, after aurora has consumed the frame's GX stream and
// before the next tick's movement runs. See the call site for why it cannot be earlier.
extern "C" void sbr_interp60_restore() {
    if (!enabled()) return;
    // Trace marker only. The restore itself is NOT done here — see the movement-dispatch comment.
    if (trace_on() && (long)VIGetRetraceCount() >= trace_start_present() && g_tracePresents <= 3) {
        trace_flush_run();
        ++g_tracePresents;
        lucent::info("i60trace", "PRESENT  (end of tick {})", g_tracePresents);
    }
}

SB_OVERRIDE(0x802fcc94, interp_test_perform, "JDrama::TViewObj::testPerform",
            "60fps interpolation (SBR_INTERP60): snapshot each actor's transform before its "
            "movement; reads guest memory only, writes nothing; always runs the real body")
